In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
corn_fn = r"/home/cholab/LabMembers/Samar/Yield_Prediction/data/monthlyTimeseriesData/2corn_monthly_timeseries_imputed_recalculated.parquet"

wheat_fn = r"/home/cholab/LabMembers/Samar/Yield_Prediction/data/monthlyTimeseriesData/2wheat_monthly_timeseries_imputed_recalculated.parquet"
soy_fn = r"/home/cholab/LabMembers/Samar/Yield_Prediction/data/monthlyTimeseriesData/2soybeans_monthly_timeseries_imputed_recalculated.parquet"
CROP = "corn"   # "soy" | "corn" | "wheat"

fn_map = {"soy": soy_fn, "corn": corn_fn, "wheat": wheat_fn}
data_path = fn_map[CROP]

df = pd.read_parquet(data_path)
print("Loaded:", data_path)
print("Shape:", df.shape)
df.head()

Loaded: /home/cholab/LabMembers/Samar/Yield_Prediction/data/monthlyTimeseriesData/2corn_monthly_timeseries_imputed_recalculated.parquet
Shape: (123228, 68)

,field,year,row,col,yield_mean,yield_std,yield_count,lon,lat,grid_crs,...,EVI,GI,NDWI,Tr_SWIR1,Tr_SWIR2,LST_K,PPT_mm,PPT_obsCount,HLS_obsCount,LST_obsCount
0,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.358719,3.750361,0.110143,1.562230,3.564016,301.612885,53.942101,30.0,13.0,2.0
1,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.500909,4.912226,0.172282,1.365183,2.988347,299.536438,84.669800,31.0,10.0,1.0
2,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.589145,6.257903,0.324979,1.691792,4.604527,304.482300,115.962097,30.0,11.0,2.0
3,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.553125,6.244105,0.292379,1.771554,5.330142,304.431040,92.278496,31.0,11.0,1.0
4,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.511105,6.177305,0.293340,2.468083,7.475546,302.171727,262.516205,31.0,10.0,1.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123228 entries, 0 to 123227
Data columns (total 68 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   field            123228 non-null  object
 1   year             123228 non-null  int64
 2   row              123228 non-null  int64
 3   col              123228 non-null  int64
 4   yield_mean       123228 non-null  float64
 5   yield_std        120064 non-null  float64
 6   yield_count      123228 non-null  int64
 7   lon              123228 non-null  float64
 8   lat              123228 non-null  float64
 9   grid_crs         123228 non-null  object
 10  template_raster  123228 non-null  object
 11  yield_meter_crs  123228 non-null  object
 12  LST_median       123228 non-null  float64
 13  LST_max          123228 non-null  float64
 14  LST_range        123228 non-null  float64
 15  NDVI_mean        123228 non-null  float64
 16  EVI_mean         123228 non-null  float64
 17  GI_mean          123228 non-null  float64
 18  NDWI_mean        123228 non-null  float64
 19  Tr_SWIR1_mean    123228 non-null  float64
 20  Tr_SWIR2_mean    123228 non-null  float64
 21  NDVI_max         123228 non-null  float64
 22  EVI_max          123228 non-null  float64
 23  GI_max           123228 non-null  float64
 24  NDWI_max         123228 non-null  float64
 25  Tr_SWIR1_max     123228 non-null  float64
 26  Tr_SWIR2_max     123228 non-null  float64
 27  NDVI_range       123228 non-null  float64
 28  EVI_range        123228 non-null  float64
 29  GI_range         123228 non-null  float64
 30  NDWI_range       123228 non-null  float64
 31  Tr_SWIR1_range   123228 non-null  float64
 32  Tr_SWIR2_range   123228 non-null  float64
 33  NDVI_obsCount    123228 non-null  float64
 34  ppt_mean         123228 non-null  float64
 35  ppt_max          123228 non-null  float64
 36  ppt_range        123228 non-null  float64
 37  ppt_total        123228 non-null  float64
 38  Soil_Sand        123228 non-null  float64
 39  Soil_Silt        123228 non-null  float64
 40  Soil_Clay        123228 non-null  float64
 41  Soil_BD          123228 non-null  float64
 42  Soil_pH          123228 non-null  float64
 43  Soil_OM          123228 non-null  float64
 44  Soil_Theta_S     123228 non-null  float64
 45  Soil_Theta_R     123228 non-null  float64
 46  Soil_Ksat        123228 non-null  float64
 47  Soil_Lambda      123228 non-null  float64
 48  Soil_Alpha       123228 non-null  float64
 49  Soil_N           123228 non-null  float64
 50  x_utm            123228 non-null  float64
 51  y_utm            123228 non-null  float64
 52  elevation        123228 non-null  float64
 53  slope            123228 non-null  float64
 54  aspect           123228 non-null  float64
 55  month            123228 non-null  int64
 56  month_index      123228 non-null  int64
 57  NDVI             123228 non-null  float64
 58  EVI              123228 non-null  float64
 59  GI               123228 non-null  float64
 60  NDWI             123228 non-null  float64
 61  Tr_SWIR1         123228 non-null  float64
 62  Tr_SWIR2         123228 non-null  float64
 63  LST_K            123228 non-null  float64
 64  PPT_mm           123228 non-null  float64
 65  PPT_obsCount     123228 non-null  float64
 66  HLS_obsCount     123228 non-null  float64
 67  LST_obsCount     123228 non-null  float64
dtypes: float64(58), int64(6), object(4)
memory usage: 63.9+ MB

In [4]:
df.rename(columns={"x_utm": "x_m", "y_utm": "y_m"}, inplace=True)
df.head()

,field,year,row,col,yield_mean,yield_std,yield_count,lon,lat,grid_crs,...,EVI,GI,NDWI,Tr_SWIR1,Tr_SWIR2,LST_K,PPT_mm,PPT_obsCount,HLS_obsCount,LST_obsCount
0,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.358719,3.750361,0.110143,1.562230,3.564016,301.612885,53.942101,30.0,13.0,2.0
1,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.500909,4.912226,0.172282,1.365183,2.988347,299.536438,84.669800,31.0,10.0,1.0
2,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.589145,6.257903,0.324979,1.691792,4.604527,304.482300,115.962097,30.0,11.0,2.0
3,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.553125,6.244105,0.292379,1.771554,5.330142,304.431040,92.278496,31.0,11.0,1.0
4,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.511105,6.177305,0.293340,2.468083,7.475546,302.171727,262.516205,31.0,10.0,1.0

In [ ]:
# month_index      241080 non-null  int64
#  57  NDVI             241080 non-null  float64
#  58  EVI              241080 non-null  float64
#  59  GI               241080 non-null  float64
#  60  NDWI             241080 non-null  float64
#  61  Tr_SWIR1         241080 non-null  float64
#  62  Tr_SWIR2         241080 non-null  float64
#  63  LST_K            241080 non-null  float64
#  64  PPT_mm           241080 non-null  float64
#  65  PPT_obsCount     241080 non-null  float64
#  66  HLS_obsCount     241080 non-null  float64
#  67  LST_obsCount     241080 non-null  float64
#  68  window

In [6]:
df.drop(columns=[
    "month_index", "PPT_mm", "month",
    "NDVI", "EVI", "GI", "NDWI", "LST_K", "Tr_SWIR1", "Tr_SWIR2", "PPT_obsCount", "HLS_obsCount", "LST_obsCount"
    ], inplace=True)
df.head()

,field,year,row,col,yield_mean,yield_std,yield_count,lon,lat,grid_crs,...,Soil_Theta_R,Soil_Ksat,Soil_Lambda,Soil_Alpha,Soil_N,x_m,y_m,elevation,slope,aspect
0,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.067641,-0.082604,0.310999,-0.364039,1.330406,331393.411954,4.320649e+06,33.366047,1.425233,83.928574
1,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.067641,-0.082604,0.310999,-0.364039,1.330406,331393.411954,4.320649e+06,33.366047,1.425233,83.928574
2,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.067641,-0.082604,0.310999,-0.364039,1.330406,331393.411954,4.320649e+06,33.366047,1.425233,83.928574
3,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.067641,-0.082604,0.310999,-0.364039,1.330406,331393.411954,4.320649e+06,33.366047,1.425233,83.928574
4,South Farm_SE-1-8-A,2021,101,51,98.718903,NaN,1,-76.947576,39.018639,EPSG:4326,...,0.067641,-0.082604,0.310999,-0.364039,1.330406,331393.411954,4.320649e+06,33.366047,1.425233,83.928574

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123228 entries, 0 to 123227
Data columns (total 55 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   field            123228 non-null  object
 1   year             123228 non-null  int64
 2   row              123228 non-null  int64
 3   col              123228 non-null  int64
 4   yield_mean       123228 non-null  float64
 5   yield_std        120064 non-null  float64
 6   yield_count      123228 non-null  int64
 7   lon              123228 non-null  float64
 8   lat              123228 non-null  float64
 9   grid_crs         123228 non-null  object
 10  template_raster  123228 non-null  object
 11  yield_meter_crs  123228 non-null  object
 12  LST_median       123228 non-null  float64
 13  LST_max          123228 non-null  float64
 14  LST_range        123228 non-null  float64
 15  NDVI_mean        123228 non-null  float64
 16  EVI_mean         123228 non-null  float64
 17  GI_mean          123228 non-null  float64
 18  NDWI_mean        123228 non-null  float64
 19  Tr_SWIR1_mean    123228 non-null  float64
 20  Tr_SWIR2_mean    123228 non-null  float64
 21  NDVI_max         123228 non-null  float64
 22  EVI_max          123228 non-null  float64
 23  GI_max           123228 non-null  float64
 24  NDWI_max         123228 non-null  float64
 25  Tr_SWIR1_max     123228 non-null  float64
 26  Tr_SWIR2_max     123228 non-null  float64
 27  NDVI_range       123228 non-null  float64
 28  EVI_range        123228 non-null  float64
 29  GI_range         123228 non-null  float64
 30  NDWI_range       123228 non-null  float64
 31  Tr_SWIR1_range   123228 non-null  float64
 32  Tr_SWIR2_range   123228 non-null  float64
 33  NDVI_obsCount    123228 non-null  float64
 34  ppt_mean         123228 non-null  float64
 35  ppt_max          123228 non-null  float64
 36  ppt_range        123228 non-null  float64
 37  ppt_total        123228 non-null  float64
 38  Soil_Sand        123228 non-null  float64
 39  Soil_Silt        123228 non-null  float64
 40  Soil_Clay        123228 non-null  float64
 41  Soil_BD          123228 non-null  float64
 42  Soil_pH          123228 non-null  float64
 43  Soil_OM          123228 non-null  float64
 44  Soil_Theta_S     123228 non-null  float64
 45  Soil_Theta_R     123228 non-null  float64
 46  Soil_Ksat        123228 non-null  float64
 47  Soil_Lambda      123228 non-null  float64
 48  Soil_Alpha       123228 non-null  float64
 49  Soil_N           123228 non-null  float64
 50  x_m              123228 non-null  float64
 51  y_m              123228 non-null  float64
 52  elevation        123228 non-null  float64
 53  slope            123228 non-null  float64
 54  aspect           123228 non-null  float64
dtypes: float64(47), int64(4), object(4)
memory usage: 51.7+ MB

In [8]:
df_seasonal = (
    df
    .groupby(["x_m", "y_m", "year"], as_index=False)
    .mean(numeric_only=True)
)

print("Original rows:", len(df))
print("Seasonal pixel-year rows:", len(df_seasonal))

Original rows: 123228
Seasonal pixel-year rows: 17468

In [ ]:
df.keys()

Index(['field', 'year', 'row', 'col', 'yield_mean', 'yield_std', 'yield_count',
       'lon', 'lat', 'grid_crs', 'template_raster', 'yield_meter_crs',
       'LST_median', 'LST_max', 'LST_range', 'NDVI_mean', 'EVI_mean',
       'GI_mean', 'NDWI_mean', 'Tr_SWIR1_mean', 'Tr_SWIR2_mean', 'NDVI_max',
       'EVI_max', 'GI_max', 'NDWI_max', 'Tr_SWIR1_max', 'Tr_SWIR2_max',
       'NDVI_range', 'EVI_range', 'GI_range', 'NDWI_range', 'Tr_SWIR1_range',
       'Tr_SWIR2_range', 'NDVI_obsCount', 'ppt_mean', 'ppt_max', 'ppt_range',
       'ppt_total', 'Soil_Sand', 'Soil_Silt', 'Soil_Clay', 'Soil_BD',
       'Soil_pH', 'Soil_OM', 'Soil_Theta_S', 'Soil_Theta_R', 'Soil_Ksat',
       'Soil_Lambda', 'Soil_Alpha', 'Soil_N', 'x_m', 'y_m', 'elevation',
       'slope', 'aspect'],
      dtype='object')

In [9]:
df_model = df_seasonal.copy()
df_model.head()

,x_m,y_m,year,row,col,yield_mean,yield_std,yield_count,lon,lat,...,Soil_OM,Soil_Theta_S,Soil_Theta_R,Soil_Ksat,Soil_Lambda,Soil_Alpha,Soil_N,elevation,slope,aspect
0,331393.411954,4.320649e+06,2021,101.0,51.0,98.718903,NaN,1.0,-76.947576,39.018639,...,-0.924384,0.433159,0.067641,-0.082604,0.310999,-0.364039,1.330406,33.366047,1.425233,83.928574
1,331394.052281,4.320679e+06,2021,100.0,51.0,89.052591,14.144032,20.0,-76.947576,39.018908,...,-0.945284,0.421844,0.057440,0.012010,0.349154,-0.217118,1.379199,34.020596,4.529707,138.333099
2,331394.692612,4.320709e+06,2021,99.0,51.0,128.879021,1.261789,2.0,-76.947576,39.019178,...,-0.978356,0.411780,0.052510,0.366437,0.356158,-0.240294,1.418346,34.808922,6.473990,133.238846
3,331413.543529,4.320499e+06,2021,106.0,52.0,164.973717,3.139631,2.0,-76.947307,39.017291,...,-0.812830,0.432628,0.068356,0.100698,0.319003,-0.368984,1.341634,40.175739,5.142047,63.324986
4,331414.183748,4.320529e+06,2021,105.0,52.0,147.956668,12.282807,6.0,-76.947307,39.017561,...,-0.894785,0.429497,0.062054,0.253108,0.330435,-0.323587,1.358419,38.299114,5.475427,55.543770

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

try:
    from xgboost import XGBRegressor
    xgb_available = True
except Exception as e:
    xgb_available = False
    print("XGBoost not available:", e)

YEAR_COL   = "year"
TARGET_RAW = "yield_mean"
FIXED_VAL_YEARS = [2023, 2019, 2024]

# Ensure log target exists
if "y_log" not in df_model.columns:
    df_model = df_model.copy()
    df_model["y_log"] = np.log1p(df_model[TARGET_RAW].astype(float))

# Features: numeric only, drop obvious non-features
drop_cols = {TARGET_RAW, "y_log", YEAR_COL, "row", "col", "lat", "lon"}
feature_cols = [c for c in df_model.columns
                if c not in drop_cols and pd.api.types.is_numeric_dtype(df_model[c])]

print("Num features:", len(feature_cols))

Num features: 45

/home/cholab/LabMembers/Samar/.venv/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [ ]:
XGB best params: {'n_estimators': 1629, 'learning_rate': 0.004670767807091202, 'max_depth': 5, 'min_child_weight': 4.819600424745501, 'subsample': 0.810291624136574, 'colsample_bytree': 0.6859053703386455, 'gamma': 1.0873018635007852, 'reg_alpha': 4.264641635924872, 'reg_lambda': 2.5028009562399314}

In [11]:
import numpy as np
import xgboost as xgb

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


def build_preprocessor(feature_cols):
    # Fit on train only (Pipeline handles this correctly)
    num_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])
    return ColumnTransformer([("num", num_pipe, feature_cols)], remainder="drop")


def make_rf_pipeline(feature_cols):
    pre = build_preprocessor(feature_cols)

    rf = RandomForestRegressor(
        n_estimators=1120,
        max_depth=22,
        min_samples_split=14,
        min_samples_leaf=5,
        max_features='log2',
        bootstrap=True
    )

    return Pipeline([("pre", pre), ("model", rf)])

    #XGB best params: {'n_estimators': 1629, 'learning_rate': 0.004670767807091202, 'max_depth': 5, 'min_child_weight': 4.819600424745501, 'subsample': 0.810291624136574, 'colsample_bytree': 0.6859053703386455, 'gamma': 1.0873018635007852, 'reg_alpha': 4.264641635924872, 'reg_lambda': 2.5028009562399314}

def make_xgb_pipeline(feature_cols):
    pre = build_preprocessor(feature_cols)

    xgb_model = XGBRegressor(
        n_estimators=1620,
        learning_rate=0.004670767807091202,
        random_state=42,
        n_jobs=-1,


        max_depth= 5,
        min_child_weight= 4.819600424745501,
        subsample = 0.8,
        colsample_bytree = 0.6859053703386455,
        gamma = 1.0873018635007852,
        reg_alpha=4.264641635924872,
        reg_lambda= 2.5028009562399314

        # ✅ GPU
        ,
        tree_method="hist",
        device="cuda",
    )
    return Pipeline([("pre", pre), ("model", xgb_model)])


def corr_sq_raw(y_true_raw, y_pred_raw):
    y_true_raw = np.asarray(y_true_raw, dtype=float)
    y_pred_raw = np.asarray(y_pred_raw, dtype=float)
    if np.std(y_true_raw) == 0 or np.std(y_pred_raw) == 0:
        return np.nan
    r = np.corrcoef(y_true_raw, y_pred_raw)[0, 1]
    return float(r * r)


def eval_raw_metrics_from_log_model(pipe, X, y_true_raw):
    """
    pipe predicts log1p(y). We inverse-transform with expm1 and compute metrics in RAW space.
    """
    yhat_log = pipe.predict(X)
    yhat_raw = np.expm1(yhat_log)

    mae = float(mean_absolute_error(y_true_raw, yhat_raw))               # ✅ raw units
    rmse = float(np.sqrt(mean_squared_error(y_true_raw, yhat_raw)))     # ✅ raw units
    r2 = float(r2_score(y_true_raw, yhat_raw))                           # ✅ raw space
    c2 = float(corr_sq_raw(y_true_raw, yhat_raw))                        # ✅ raw space

    return {"mae": mae, "rmse": rmse, "r2": r2, "corr2": c2}


def get_splits(df, test_year):
    all_years = sorted(df[YEAR_COL].unique())

    val_years_used = [y for y in FIXED_VAL_YEARS if y != test_year]
    train_years = [y for y in all_years if (y != test_year and y not in val_years_used)]

    train_df = df[df[YEAR_COL].isin(train_years)].copy()
    val_df = df[df[YEAR_COL].isin(val_years_used)].copy()
    test_df = df[df[YEAR_COL] == test_year].copy()
    return train_df, val_df, test_df, val_years_used


def compute_split_metrics(pipe, X, y_log, y_raw):
    """
    pipe is trained on log targets. This returns metrics on RAW space after expm1.
    """
    yhat_log = pipe.predict(X)
    yhat_raw = np.expm1(yhat_log)

    out = {
        "mae": float(mean_absolute_error(y_raw, yhat_raw)),
        "rmse": float(np.sqrt(mean_squared_error(y_raw, yhat_raw))),
        "r2": float(r2_score(y_raw, yhat_raw)),
        "corr2": float(corr_sq_raw(y_raw, yhat_raw)),
    }
    return out


# ============================================================
# ✅ ADDITION: XGBoost early stopping + GPU (version-safe)
# ============================================================

def fit_xgb_pipeline_with_early_stopping(
    pipe,
    X_train, y_train_log,
    X_val, y_val_log,
    early_stopping_rounds=50
):
    """
    Fit XGBoost with early stopping using native xgb.train,
    mirroring the tuning-time implementation exactly.
    """

    pre = pipe.named_steps["pre"]
    model = pipe.named_steps["model"]

    # preprocess
    X_tr_t = pre.fit_transform(X_train)
    X_va_t = pre.transform(X_val)

    # DMatrix
    dtrain = xgb.DMatrix(X_tr_t, label=y_train_log)
    dvalid = xgb.DMatrix(X_va_t, label=y_val_log)


    # native xgb params (same as tuning)
    xgb_params = {
        "objective": "reg:squarederror",
        "eval_metric": "rmse",
        "seed": model.random_state,

        # ✅ GPU
        "tree_method": "hist",
        "device": "cuda",

        # hyperparameters
        "eta": model.learning_rate,
        "max_depth": int(model.max_depth),
        "subsample": float(model.subsample),
        "colsample_bytree": float(model.colsample_bytree),
        "lambda": float(model.reg_lambda),
    }

    booster = xgb.train(
        params=xgb_params,
        dtrain=dtrain,
        num_boost_round=model.n_estimators,
        evals=[(dvalid, "valid")],
        early_stopping_rounds=early_stopping_rounds,
        verbose_eval=False
    )

    return booster, pre

In [12]:
def plot_learning_curve_fold(make_pipe_fn, train_df, val_df, title,
                             train_fracs=(0.1, 0.2, 0.4, 0.6, 0.8, 1.0),
                             seed=42):

    rng = np.random.default_rng(seed)

    # Keep as DataFrames
    X_val = val_df[feature_cols]
    y_val_raw = val_df[TARGET_RAW].values

    n = len(train_df)
    sizes = [max(200, int(n*f)) for f in train_fracs]  # ensure not too tiny
    sizes = sorted(set([min(s, n) for s in sizes]))

    train_mae, val_mae = [], []

    for s in sizes:
        # subsample train
        idx = rng.choice(n, size=s, replace=False)
        sub = train_df.iloc[idx]

        X_tr = sub[feature_cols]
        y_tr_log = sub["y_log"].values
        y_tr_raw = sub[TARGET_RAW].values

        pipe = make_pipe_fn(feature_cols)
        pipe.fit(X_tr, y_tr_log)

        m_tr = compute_split_metrics(pipe, X_tr, y_tr_log, y_tr_raw)["mae"]
        m_va = compute_split_metrics(pipe, X_val, val_df["y_log"].values, y_val_raw)["mae"]

        train_mae.append(m_tr)
        val_mae.append(m_va)

    plt.figure()
    plt.plot(sizes, train_mae, marker="o", label="Train MAE (raw)")
    plt.plot(sizes, val_mae, marker="o", label="Val MAE (raw)")
    plt.xlabel("Training samples")
    plt.ylabel("MAE (raw yield units)")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.show()

In [13]:
rows = []
all_years = sorted(df_model["year"].unique())

for test_year in all_years:
    train_df, val_df, test_df, val_years_used = get_splits(df_model, test_year)

    # DataFrames for X, raw targets for metrics
    X_train = train_df[feature_cols]
    y_train_raw = train_df[TARGET_RAW].values

    X_val = val_df[feature_cols]
    y_val_raw = val_df[TARGET_RAW].values

    X_test = test_df[feature_cols]
    y_test_raw = test_df[TARGET_RAW].values

    # ---------------- RF ----------------
    rf_pipe = make_rf_pipeline(feature_cols)
    rf_pipe.fit(X_train, train_df["y_log"].values)  # training target in log space

    rf_train = eval_raw_metrics_from_log_model(rf_pipe, X_train, y_train_raw)
    rf_val   = eval_raw_metrics_from_log_model(rf_pipe, X_val,   y_val_raw)  if len(val_df) else {"mae":np.nan,"rmse":np.nan,"r2":np.nan,"corr2":np.nan}
    rf_test  = eval_raw_metrics_from_log_model(rf_pipe, X_test,  y_test_raw)

    rows.append({
        "test_year": int(test_year),
        "model": "RF",
        "val_years_used": ",".join(map(str, val_years_used)),
        "train_size": int(len(train_df)),
        "val_size": int(len(val_df)),
        "test_size": int(len(test_df)),
        "train_mae": rf_train["mae"], "train_rmse": rf_train["rmse"], "train_r2": rf_train["r2"], "train_corr2": rf_train["corr2"],
        "val_mae":   rf_val["mae"],   "val_rmse":   rf_val["rmse"],   "val_r2":   rf_val["r2"],   "val_corr2":   rf_val["corr2"],
        "test_mae":  rf_test["mae"],  "test_rmse":  rf_test["rmse"],  "test_r2":  rf_test["r2"],  "test_corr2":  rf_test["corr2"],
    })

    print(f"\n=== {test_year} | RF | ValYears={val_years_used} ===")
    print(f"Train: MAE={rf_train['mae']:.3f} RMSE={rf_train['rmse']:.3f} R2={rf_train['r2']:.3f} Corr^2={rf_train['corr2']:.3f}")
    print(f"Val  : MAE={rf_val['mae']:.3f} RMSE={rf_val['rmse']:.3f} R2={rf_val['r2']:.3f} Corr^2={rf_val['corr2']:.3f}")
    print(f"Test : MAE={rf_test['mae']:.3f} RMSE={rf_test['rmse']:.3f} R2={rf_test['r2']:.3f} Corr^2={rf_test['corr2']:.3f}")

    # ---------------- XGB ----------------
    if xgb_available:
        xgb_pipe = make_xgb_pipeline(feature_cols)

        # ✅ EARLY STOPPING + GPU (same as tuning)
        booster, pre = fit_xgb_pipeline_with_early_stopping(
            xgb_pipe,
            X_train, train_df["y_log"].values,
            X_val,   val_df["y_log"].values,
            early_stopping_rounds=50
        )

        # --- predict TRAIN ---
        X_train_t = pre.transform(X_train)
        dtrain = xgb.DMatrix(X_train_t)
        yhat_train_log = booster.predict(dtrain)
        xgb_train = eval_raw_metrics_from_log_preds(y_train_raw, yhat_train_log)

        # --- predict VAL ---
        if len(val_df):
            X_val_t = pre.transform(X_val)
            dval = xgb.DMatrix(X_val_t)
            yhat_val_log = booster.predict(dval)
            xgb_val = eval_raw_metrics_from_log_preds(y_val_raw, yhat_val_log)
        else:
            xgb_val = {"mae":np.nan,"rmse":np.nan,"r2":np.nan,"corr2":np.nan}

        # --- predict TEST ---
        X_test_t = pre.transform(X_test)
        dtest = xgb.DMatrix(X_test_t)
        yhat_test_log = booster.predict(dtest)
        xgb_test = eval_raw_metrics_from_log_preds(y_test_raw, yhat_test_log)

        rows.append({
            "test_year": int(test_year),
            "model": "XGB",
            "val_years_used": ",".join(map(str, val_years_used)),
            "train_size": int(len(train_df)),
            "val_size": int(len(val_df)),
            "test_size": int(len(test_df)),
            "train_mae": xgb_train["mae"], "train_rmse": xgb_train["rmse"], "train_r2": xgb_train["r2"], "train_corr2": xgb_train["corr2"],
            "val_mae":   xgb_val["mae"],   "val_rmse":   xgb_val["rmse"],   "val_r2":   xgb_val["r2"],   "val_corr2":   xgb_val["corr2"],
            "test_mae":  xgb_test["mae"],  "test_rmse":  xgb_test["rmse"],  "test_r2":  xgb_test["r2"],  "test_corr2":  xgb_test["corr2"],
        })

        print(f"\n=== {test_year} | XGB | ValYears={val_years_used} ===")
        print(f"Train: MAE={xgb_train['mae']:.3f} RMSE={xgb_train['rmse']:.3f} R2={xgb_train['r2']:.3f} Corr^2={xgb_train['corr2']:.3f}")
        print(f"Val  : MAE={xgb_val['mae']:.3f} RMSE={xgb_val['rmse']:.3f} R2={xgb_val['r2']:.3f} Corr^2={xgb_val['corr2']:.3f}")
        print(f"Test : MAE={xgb_test['mae']:.3f} RMSE={xgb_test['rmse']:.3f} R2={xgb_test['r2']:.3f} Corr^2={xgb_test['corr2']:.3f}")

res_all = pd.DataFrame(rows).sort_values(["model", "test_year"]).reset_index(drop=True)
res_all

ValueError: Input y contains NaN.

### Hyper parameter tuning

In [14]:
import numpy as np
import pandas as pd

from sklearn.model_selection import GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

try:
    from xgboost import XGBRegressor
    xgb_available = True
except Exception as e:
    xgb_available = False
    print("XGBoost not available:", e)

# ---- REQUIRED: df_model, feature_cols, YEAR_COL, TARGET_RAW, y_log already exist ----
# YEAR_COL="year", TARGET_RAW="yield_mean"
# df_model["y_log"] = np.log1p(df_model[TARGET_RAW])

def corr_sq(y_true, y_pred):
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    if np.std(y_true) == 0 or np.std(y_pred) == 0:
        return np.nan
    r = np.corrcoef(y_true, y_pred)[0, 1]
    return float(r*r)

def eval_raw_metrics_from_log_preds(y_true_raw, y_pred_log):
    y_pred_raw = np.expm1(y_pred_log)
    return {
        "mae":  float(mean_absolute_error(y_true_raw, y_pred_raw)),
        "rmse": float(np.sqrt(mean_squared_error(y_true_raw, y_pred_raw))),
        "r2":   float(r2_score(y_true_raw, y_pred_raw)),
        "corr2": float(corr_sq(y_true_raw, y_pred_raw)),
    }

def build_preprocessor(feature_cols):
    num_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])
    return ColumnTransformer([("num", num_pipe, feature_cols)], remainder="drop")

def make_rf_pipeline(feature_cols, params):
    pre = build_preprocessor(feature_cols)
    rf = RandomForestRegressor(
        random_state=42,
        n_jobs=-1,
        **params
    )
    return Pipeline([("pre", pre), ("model", rf)])

def make_xgb_pipeline(feature_cols, params):
    pre = build_preprocessor(feature_cols)
    xgb = XGBRegressor(
        random_state=42,
        n_jobs=-1,
        tree_method="hist",
        **params
    )
    return Pipeline([("pre", pre), ("model", xgb)])

In [15]:
def year_group_cv_score(df, feature_cols, params, model_kind="rf", n_splits=5, seed=42):
    """
    Returns mean CV MAE (raw) across year-group folds, plus mean RMSE/R2/Corr2 for tracking.
    """
    X = df[feature_cols]                 # keep as DataFrame
    y_log = df["y_log"].values
    y_raw = df["yield_mean"].values      # raw target for metrics
    groups = df["year"].values

    gkf = GroupKFold(n_splits=n_splits)

    fold_metrics = []
    for tr_idx, va_idx in gkf.split(X, y_log, groups=groups):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr_log = y_log[tr_idx]
        y_va_raw = y_raw[va_idx]

        if model_kind == "rf":
            pipe = make_rf_pipeline(feature_cols, params)
        else:
            pipe = make_xgb_pipeline(feature_cols, params)

        pipe.fit(X_tr, y_tr_log)
        yhat_va_log = pipe.predict(X_va)
        m = eval_raw_metrics_from_log_preds(y_va_raw, yhat_va_log)
        fold_metrics.append(m)

    out = {
        "mae":  float(np.mean([m["mae"] for m in fold_metrics])),
        "rmse": float(np.mean([m["rmse"] for m in fold_metrics])),
        "r2":   float(np.mean([m["r2"] for m in fold_metrics])),
        "corr2": float(np.mean([m["corr2"] for m in fold_metrics])),
    }
    return out

In [16]:
import xgboost as xgb
from sklearn.model_selection import GroupKFold

def score_params_year_cv_xgb_earlystop(df, feature_cols, params, n_splits=5, early_stopping_rounds=50):
    """
    Robust tuning scorer for XGB with:
    - GroupKFold by year
    - train on log1p(y)
    - evaluate metrics on raw y (expm1(pred))
    - early stopping via xgb.train (native API, version-safe)
    - GPU via tree_method=gpu_hist
    """
    X = df[feature_cols]
    y_log = df["y_log"].values
    y_raw = df[TARGET_RAW].values
    groups = df[YEAR_COL].values

    gkf = GroupKFold(n_splits=n_splits)
    fold_metrics = []

    for tr_idx, va_idx in gkf.split(X, y_log, groups):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr_log = y_log[tr_idx]
        y_va_log = y_log[va_idx]
        y_va_raw = y_raw[va_idx]

        # --- preprocess on train only ---
        pre = build_preprocessor(feature_cols)
        X_tr_t = pre.fit_transform(X_tr)
        X_va_t = pre.transform(X_va)

        # --- DMatrix ---
        dtrain = xgb.DMatrix(X_tr_t, label=y_tr_log)
        dvalid = xgb.DMatrix(X_va_t, label=y_va_log)

        # --- xgb.train params (native) ---
        # Map sklearn-style names to native names when needed
        xgb_params = {
            "objective": "reg:squarederror",
            "eval_metric": "rmse",
            "seed": 42,

            # ✅ GPU
            "tree_method": "hist",
            "device": "cuda",


            # from Optuna
            "eta": params["learning_rate"],
            "max_depth": int(params["max_depth"]),
            "min_child_weight": float(params["min_child_weight"]),
            "subsample": float(params["subsample"]),
            "colsample_bytree": float(params["colsample_bytree"]),
            "gamma": float(params["gamma"]),
            "alpha": float(params["reg_alpha"]),
            "lambda": float(params["reg_lambda"]),
        }

        num_boost_round = int(params.get("n_estimators", 5000))

        booster = xgb.train(
            params=xgb_params,
            dtrain=dtrain,
            num_boost_round=num_boost_round,
            evals=[(dvalid, "valid")],
            early_stopping_rounds=early_stopping_rounds,
            verbose_eval=False
        )

        # predict log, evaluate raw
        yhat_va_log = booster.predict(dvalid)
        m = eval_raw_metrics_from_log_preds(y_va_raw, yhat_va_log)
        fold_metrics.append(m)

    return {k: float(np.mean([m[k] for m in fold_metrics])) for k in fold_metrics[0]}

In [17]:
import optuna

def tune_rf_optuna(df, feature_cols, n_trials=50, n_splits=5):
    def objective(trial):
        params = {
            "n_estimators": trial.suggest_int("n_estimators", 100, 1400),
            "max_depth": trial.suggest_int("max_depth", 1, 40),
            "min_samples_split": trial.suggest_int("min_samples_split", 2, 30),
            "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 15),
            "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", 0.3, 0.5, 0.8]),
            "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
        }
        m = year_group_cv_score(df, feature_cols, params, model_kind="rf", n_splits=n_splits)
        # Optimize raw MAE
        trial.set_user_attr("rmse", m["rmse"])
        trial.set_user_attr("r2", m["r2"])
        trial.set_user_attr("corr2", m["corr2"])
        return m["mae"]

    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

    best_params = study.best_params
    best_mae = study.best_value
    best_meta = study.best_trial.user_attrs
    return study, best_params, best_mae, best_meta


def tune_xgb_optuna(df, feature_cols, n_trials=60, n_splits=5):
    if not xgb_available:
        raise RuntimeError("XGBoost not available in this environment.")

    def objective(trial):
        params = {
            "n_estimators": trial.suggest_int("n_estimators", 100, 2500),
            "learning_rate": trial.suggest_float("learning_rate", 0.00001, 0.01, log=True),
            "max_depth": trial.suggest_int("max_depth", 3, 10),
            "min_child_weight": trial.suggest_float("min_child_weight", 1.0, 20.0, log=True),
            "subsample": trial.suggest_float("subsample", 0.6, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
            "gamma": trial.suggest_float("gamma", 0.0, 5.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 5.0),
            "reg_lambda": trial.suggest_float("reg_lambda", 0.1, 10.0, log=True),
        }
        m = score_params_year_cv_xgb_earlystop(
            df, feature_cols, params,
            n_splits=n_splits,
            early_stopping_rounds=50
        )
        trial.set_user_attr("rmse", m["rmse"])
        trial.set_user_attr("r2", m["r2"])
        trial.set_user_attr("corr2", m["corr2"])
        return m["mae"]

    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

    best_params = study.best_params
    best_mae = study.best_value
    best_meta = study.best_trial.user_attrs
    return study, best_params, best_mae, best_meta

In [ ]:
from sklearn.model_selection import GroupKFold

In [22]:

# (Optional but recommended) restrict tuning to the years you actually plan to train on most of the time
# e.g., use all years 2014-2024:
df_tune = df_model.copy()

target_col = "yield_mean"

# 1) drop missing targets
df_tune = df_tune.dropna(subset=[target_col])

# 2) remove sentinel values if you use them (common in rasters)
df_tune = df_tune[df_tune[target_col] != -9999]   # add others if needed

# 3) enforce positive for log (choose one approach)
df_tune = df_tune[df_tune[target_col] > 0]        # strict (safest for log)

# optional sanity check
assert df_tune[target_col].isna().sum() == 0
assert (df_tune[target_col] <= 0).sum() == 0

rf_study, rf_best_params, rf_best_mae, rf_best_meta = tune_rf_optuna(
    df_tune, feature_cols, n_trials=50, n_splits=5
)
print("\nRF best params:", rf_best_params)
print("RF CV best MAE:", rf_best_mae)
print("RF CV meta:", rf_best_meta)

if xgb_available:
    xgb_study, xgb_best_params, xgb_best_mae, xgb_best_meta = tune_xgb_optuna(
        df_tune, feature_cols, n_trials=60, n_splits=5
    )
    print("\nXGB best params:", xgb_best_params)
    print("XGB CV best MAE:", xgb_best_mae)
    print("XGB CV meta:", xgb_best_meta)

[I 2026-01-25 14:31:07,748] A new study created in memory with name: no-name-0477a0a7-eb41-4876-ae5c-a8e316281b57

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-25 14:31:13,814] Trial 0 finished with value: 35.2793812311361 and parameters: {'n_estimators': 208, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': True}. Best is trial 0 with value: 35.2793812311361.
[I 2026-01-25 14:31:33,199] Trial 1 finished with value: 34.89508618706247 and parameters: {'n_estimators': 1149, 'max_depth': 22, 'min_samples_split': 23, 'min_samples_leaf': 14, 'max_features': 0.3, 'bootstrap': True}. Best is trial 1 with value: 34.89508618706247.
[I 2026-01-25 14:31:43,309] Trial 2 finished with value: 35.09954462571255 and parameters: {'n_estimators': 988, 'max_depth': 3, 'min_samples_split': 24, 'min_samples_leaf': 3, 'max_features': 0.3, 'bootstrap': False}. Best is trial 1 with value: 34.89508618706247.
[I 2026-01-25 14:31:46,517] Trial 3 finished with value: 34.8407172024135 and parameters: {'n_estimators': 124, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 3 with value: 34.8407172024135.
[I 2026-01-25 14:32:08,152] Trial 4 finished with value: 36.54399764970331 and parameters: {'n_estimators': 552, 'max_depth': 29, 'min_samples_split': 29, 'min_samples_leaf': 7, 'max_features': 0.8, 'bootstrap': True}. Best is trial 3 with value: 34.8407172024135.
[I 2026-01-25 14:32:16,649] Trial 5 finished with value: 34.38518894252867 and parameters: {'n_estimators': 462, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': True}. Best is trial 5 with value: 34.38518894252867.
[I 2026-01-25 14:32:23,142] Trial 6 finished with value: 35.02999854392325 and parameters: {'n_estimators': 413, 'max_depth': 31, 'min_samples_split': 16, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False}. Best is trial 5 with value: 34.38518894252867.
[I 2026-01-25 14:32:32,713] Trial 7 finished with value: 34.405579874250876 and parameters: {'n_estimators': 536, 'max_depth': 5, 'min_samples_split': 21, 'min_samples_leaf': 11, 'max_features': 0.3, 'bootstrap': True}. Best is trial 5 with value: 34.38518894252867.
[I 2026-01-25 14:33:05,383] Trial 8 finished with value: 36.684434468524444 and parameters: {'n_estimators': 1055, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False}. Best is trial 5 with value: 34.38518894252867.
[I 2026-01-25 14:33:26,429] Trial 9 finished with value: 35.764135793557266 and parameters: {'n_estimators': 1313, 'max_depth': 2, 'min_samples_split': 26, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': True}. Best is trial 5 with value: 34.38518894252867.
[I 2026-01-25 14:33:36,418] Trial 10 finished with value: 34.55580222914038 and parameters: {'n_estimators': 777, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': False}. Best is trial 5 with value: 34.38518894252867.
[I 2026-01-25 14:33:46,680] Trial 11 finished with value: 34.38985597982887 and parameters: {'n_estimators': 606, 'max_depth': 17, 'min_samples_split': 18, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 5 with value: 34.38518894252867.
[I 2026-01-25 14:33:58,940] Trial 12 finished with value: 34.32900703694942 and parameters: {'n_estimators': 709, 'max_depth': 40, 'min_samples_split': 17, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:34:12,899] Trial 13 finished with value: 34.35780939890121 and parameters: {'n_estimators': 821, 'max_depth': 39, 'min_samples_split': 12, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:34:26,453] Trial 14 finished with value: 34.36791538732342 and parameters: {'n_estimators': 797, 'max_depth': 40, 'min_samples_split': 11, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:34:59,573] Trial 15 finished with value: 36.38706165007713 and parameters: {'n_estimators': 912, 'max_depth': 39, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': 0.8, 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:35:11,434] Trial 16 finished with value: 34.43958996257826 and parameters: {'n_estimators': 697, 'max_depth': 34, 'min_samples_split': 14, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:35:17,912] Trial 17 finished with value: 34.33640078544534 and parameters: {'n_estimators': 326, 'max_depth': 36, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:35:23,204] Trial 18 finished with value: 34.58920234912435 and parameters: {'n_estimators': 333, 'max_depth': 26, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:35:29,201] Trial 19 finished with value: 34.35380264635484 and parameters: {'n_estimators': 292, 'max_depth': 35, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:35:40,402] Trial 20 finished with value: 34.759680494902 and parameters: {'n_estimators': 632, 'max_depth': 35, 'min_samples_split': 20, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:35:46,208] Trial 21 finished with value: 34.357195114123584 and parameters: {'n_estimators': 294, 'max_depth': 34, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:35:51,785] Trial 22 finished with value: 34.351445397027575 and parameters: {'n_estimators': 264, 'max_depth': 36, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:35:54,717] Trial 23 finished with value: 34.591345958488354 and parameters: {'n_estimators': 104, 'max_depth': 28, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:36:02,707] Trial 24 finished with value: 34.52184632145125 and parameters: {'n_estimators': 419, 'max_depth': 37, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:36:12,621] Trial 25 finished with value: 36.33336444015506 and parameters: {'n_estimators': 209, 'max_depth': 25, 'min_samples_split': 16, 'min_samples_leaf': 12, 'max_features': 0.8, 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:36:19,708] Trial 26 finished with value: 34.582709093413726 and parameters: {'n_estimators': 485, 'max_depth': 32, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': False}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:36:26,575] Trial 27 finished with value: 34.39679194272286 and parameters: {'n_estimators': 355, 'max_depth': 37, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:36:31,443] Trial 28 finished with value: 34.538045934135894 and parameters: {'n_estimators': 234, 'max_depth': 32, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:37:03,595] Trial 29 finished with value: 35.8746253230231 and parameters: {'n_estimators': 1303, 'max_depth': 23, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': 0.5, 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:37:14,908] Trial 30 finished with value: 34.473680075988284 and parameters: {'n_estimators': 654, 'max_depth': 37, 'min_samples_split': 4, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:37:20,397] Trial 31 finished with value: 34.34457846234296 and parameters: {'n_estimators': 270, 'max_depth': 40, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:37:24,452] Trial 32 finished with value: 34.54739931068527 and parameters: {'n_estimators': 184, 'max_depth': 40, 'min_samples_split': 7, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:37:32,917] Trial 33 finished with value: 35.16423182312734 and parameters: {'n_estimators': 372, 'max_depth': 37, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 0.3, 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:37:38,224] Trial 34 finished with value: 34.346824819251324 and parameters: {'n_estimators': 261, 'max_depth': 30, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:37:43,528] Trial 35 finished with value: 35.409803727034856 and parameters: {'n_estimators': 169, 'max_depth': 29, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 0.3, 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:38:23,514] Trial 36 finished with value: 36.23156315985513 and parameters: {'n_estimators': 1172, 'max_depth': 31, 'min_samples_split': 13, 'min_samples_leaf': 12, 'max_features': 0.8, 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:38:30,722] Trial 37 finished with value: 34.45905103742801 and parameters: {'n_estimators': 538, 'max_depth': 33, 'min_samples_split': 11, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:38:39,170] Trial 38 finished with value: 34.35228932078746 and parameters: {'n_estimators': 457, 'max_depth': 40, 'min_samples_split': 18, 'min_samples_leaf': 13, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:39:01,847] Trial 39 finished with value: 35.82812013715663 and parameters: {'n_estimators': 874, 'max_depth': 29, 'min_samples_split': 22, 'min_samples_leaf': 7, 'max_features': 0.5, 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:39:06,974] Trial 40 finished with value: 35.18890738563677 and parameters: {'n_estimators': 139, 'max_depth': 38, 'min_samples_split': 8, 'min_samples_leaf': 11, 'max_features': 0.3, 'bootstrap': False}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:39:12,584] Trial 41 finished with value: 34.352449430928935 and parameters: {'n_estimators': 274, 'max_depth': 36, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:39:17,329] Trial 42 finished with value: 34.346923446799074 and parameters: {'n_estimators': 230, 'max_depth': 35, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:39:24,702] Trial 43 finished with value: 34.56899351340659 and parameters: {'n_estimators': 388, 'max_depth': 34, 'min_samples_split': 24, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:39:31,129] Trial 44 finished with value: 34.35735257506495 and parameters: {'n_estimators': 328, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:39:35,530] Trial 45 finished with value: 34.54738961752732 and parameters: {'n_estimators': 221, 'max_depth': 14, 'min_samples_split': 30, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:39:52,850] Trial 46 finished with value: 34.38157776355954 and parameters: {'n_estimators': 1026, 'max_depth': 38, 'min_samples_split': 12, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:40:03,049] Trial 47 finished with value: 35.21049821874631 and parameters: {'n_estimators': 483, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.
[I 2026-01-25 14:40:34,215] Trial 48 finished with value: 36.9803813432746 and parameters: {'n_estimators': 577, 'max_depth': 27, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': 0.8, 'bootstrap': False}. Best is trial 12 with value: 34.32900703694942.

[I 2026-01-25 14:40:37,835] A new study created in memory with name: no-name-bce317f4-c7ea-4bd7-80ef-6745dcb24f8e

[I 2026-01-25 14:40:37,827] Trial 49 finished with value: 34.404426131738646 and parameters: {'n_estimators': 151, 'max_depth': 39, 'min_samples_split': 19, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 12 with value: 34.32900703694942.

RF best params: {'n_estimators': 709, 'max_depth': 40, 'min_samples_split': 17, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}
RF CV best MAE: 34.32900703694942
RF CV meta: {'rmse': 42.37380306730396, 'r2': 0.2727519260611609, 'corr2': 0.4323007870502031}

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-01-25 14:40:43,831] Trial 0 finished with value: 35.6556151726428 and parameters: {'n_estimators': 1954, 'learning_rate': 0.006785669499049411, 'max_depth': 4, 'min_child_weight': 2.4117130860712943, 'subsample': 0.7335683160494466, 'colsample_bytree': 0.8974508263234491, 'gamma': 4.706717335968395, 'reg_alpha': 4.177675853128987, 'reg_lambda': 0.11038607880733657}. Best is trial 0 with value: 35.6556151726428.
[I 2026-01-25 14:40:51,433] Trial 1 finished with value: 35.33965839797759 and parameters: {'n_estimators': 2157, 'learning_rate': 0.007482227162894692, 'max_depth': 4, 'min_child_weight': 1.2191772186541368, 'subsample': 0.7978270353239432, 'colsample_bytree': 0.6095919238023685, 'gamma': 1.1968460518043305, 'reg_alpha': 4.398397152104386, 'reg_lambda': 1.4333470295984794}. Best is trial 1 with value: 35.33965839797759.
[I 2026-01-25 14:41:10,859] Trial 2 finished with value: 42.44229145837331 and parameters: {'n_estimators': 1020, 'learning_rate': 0.00017382752652370358, 'max_depth': 7, 'min_child_weight': 1.7339227861438957, 'subsample': 0.7614505588713398, 'colsample_bytree': 0.9235400453394293, 'gamma': 4.6667227167066345, 'reg_alpha': 3.755485811741248, 'reg_lambda': 0.1680736578485404}. Best is trial 1 with value: 35.33965839797759.
[I 2026-01-25 14:41:28,964] Trial 3 finished with value: 38.73536496760091 and parameters: {'n_estimators': 2229, 'learning_rate': 0.00032849077720080693, 'max_depth': 3, 'min_child_weight': 18.646188360647876, 'subsample': 0.8148784948280416, 'colsample_bytree': 0.8379117440994517, 'gamma': 4.893028842811434, 'reg_alpha': 1.9504875412782159, 'reg_lambda': 0.2651212717743467}. Best is trial 1 with value: 35.33965839797759.
[I 2026-01-25 14:41:57,381] Trial 4 finished with value: 41.94938468569452 and parameters: {'n_estimators': 1529, 'learning_rate': 0.00014264600337883735, 'max_depth': 7, 'min_child_weight': 14.936710441959457, 'subsample': 0.7579116141190059, 'colsample_bytree': 0.6691000924780834, 'gamma': 3.9565606686132164, 'reg_alpha': 0.7268184919136295, 'reg_lambda': 1.6852959234823541}. Best is trial 1 with value: 35.33965839797759.
[I 2026-01-25 14:42:16,671] Trial 5 finished with value: 44.25085459862153 and parameters: {'n_estimators': 1268, 'learning_rate': 3.198744276743222e-05, 'max_depth': 6, 'min_child_weight': 1.482867281832621, 'subsample': 0.9018156986516879, 'colsample_bytree': 0.6114809166484082, 'gamma': 4.346535742100793, 'reg_alpha': 0.5276348257329722, 'reg_lambda': 1.3571397659011857}. Best is trial 1 with value: 35.33965839797759.
[I 2026-01-25 14:42:25,615] Trial 6 finished with value: 35.27324372051112 and parameters: {'n_estimators': 1525, 'learning_rate': 0.007691536277850133, 'max_depth': 10, 'min_child_weight': 8.038098526081743, 'subsample': 0.7691325929301764, 'colsample_bytree': 0.7740022442172726, 'gamma': 1.8981844892119577, 'reg_alpha': 0.5469290977348318, 'reg_lambda': 0.8001423008058823}. Best is trial 6 with value: 35.27324372051112.
[I 2026-01-25 14:42:43,519] Trial 7 finished with value: 43.37749132309777 and parameters: {'n_estimators': 869, 'learning_rate': 0.00011903131921721438, 'max_depth': 8, 'min_child_weight': 1.3256833369750685, 'subsample': 0.7981594607187681, 'colsample_bytree': 0.6801240244063432, 'gamma': 4.680806933647058, 'reg_alpha': 1.1920051770702889, 'reg_lambda': 2.035902113490383}. Best is trial 6 with value: 35.27324372051112.
[I 2026-01-25 14:43:40,529] Trial 8 finished with value: 40.32437402686194 and parameters: {'n_estimators': 2156, 'learning_rate': 0.00017846948076210252, 'max_depth': 10, 'min_child_weight': 19.52410640422713, 'subsample': 0.8614921973555423, 'colsample_bytree': 0.7597176469997635, 'gamma': 2.517772181498894, 'reg_alpha': 0.5817096199763461, 'reg_lambda': 6.411757225706443}. Best is trial 6 with value: 35.27324372051112.
[I 2026-01-25 14:44:31,882] Trial 9 finished with value: 38.377703736615665 and parameters: {'n_estimators': 2188, 'learning_rate': 0.0003356707349310039, 'max_depth': 9, 'min_child_weight': 2.773134549371174, 'subsample': 0.603881104461609, 'colsample_bytree': 0.9243879592730884, 'gamma': 1.666190529779158, 'reg_alpha': 4.372119549525787, 'reg_lambda': 0.113379197629148}. Best is trial 6 with value: 35.27324372051112.
[I 2026-01-25 14:44:43,257] Trial 10 finished with value: 40.882988834043644 and parameters: {'n_estimators': 201, 'learning_rate': 0.0016890771089163273, 'max_depth': 10, 'min_child_weight': 6.888396884159043, 'subsample': 0.9740382888290189, 'colsample_bytree': 0.9990440737452015, 'gamma': 0.1627589626835011, 'reg_alpha': 2.6790324769460834, 'reg_lambda': 0.5255837479419446}. Best is trial 6 with value: 35.27324372051112.
[I 2026-01-25 14:44:49,306] Trial 11 finished with value: 35.49552066709752 and parameters: {'n_estimators': 1700, 'learning_rate': 0.009272315957266759, 'max_depth': 5, 'min_child_weight': 6.927495076843604, 'subsample': 0.6778630574098221, 'colsample_bytree': 0.7583695152528469, 'gamma': 1.4041008435393503, 'reg_alpha': 3.0660622219348643, 'reg_lambda': 0.622376466683257}. Best is trial 6 with value: 35.27324372051112.
[I 2026-01-25 14:45:02,201] Trial 12 finished with value: 35.61872881353483 and parameters: {'n_estimators': 2464, 'learning_rate': 0.00219001376936926, 'max_depth': 3, 'min_child_weight': 5.42759022143675, 'subsample': 0.685163243716093, 'colsample_bytree': 0.6944844968640449, 'gamma': 2.4262982387356162, 'reg_alpha': 4.951818991359785, 'reg_lambda': 3.492829622566477}. Best is trial 6 with value: 35.27324372051112.
[I 2026-01-25 14:45:16,996] Trial 13 finished with value: 35.312976142538645 and parameters: {'n_estimators': 1701, 'learning_rate': 0.002032869699124272, 'max_depth': 5, 'min_child_weight': 8.816649941236697, 'subsample': 0.8715548326412477, 'colsample_bytree': 0.6011792100682611, 'gamma': 0.5371384915045305, 'reg_alpha': 1.7359708837490606, 'reg_lambda': 0.7418138889253091}. Best is trial 6 with value: 35.27324372051112.
[I 2026-01-25 14:45:38,436] Trial 14 finished with value: 35.265375841114256 and parameters: {'n_estimators': 1638, 'learning_rate': 0.0017617092351005959, 'max_depth': 6, 'min_child_weight': 11.70027615001185, 'subsample': 0.9405889855189131, 'colsample_bytree': 0.8255694630221575, 'gamma': 0.42968119528045146, 'reg_alpha': 1.6917459656836493, 'reg_lambda': 0.5295848202360258}. Best is trial 14 with value: 35.265375841114256.
[I 2026-01-25 14:46:03,993] Trial 15 finished with value: 36.314524530865114 and parameters: {'n_estimators': 1178, 'learning_rate': 0.0011670141847238305, 'max_depth': 8, 'min_child_weight': 11.642415823104876, 'subsample': 0.9754016401677199, 'colsample_bytree': 0.8189301507065736, 'gamma': 3.0391252302173823, 'reg_alpha': 0.144089380093805, 'reg_lambda': 0.3132226669724629}. Best is trial 14 with value: 35.265375841114256.
[I 2026-01-25 14:46:13,475] Trial 16 finished with value: 35.2599739402343 and parameters: {'n_estimators': 619, 'learning_rate': 0.004183814147562783, 'max_depth': 6, 'min_child_weight': 4.245010611175893, 'subsample': 0.9089933394279593, 'colsample_bytree': 0.7677715229045413, 'gamma': 0.9268906140903139, 'reg_alpha': 1.2547456399153425, 'reg_lambda': 0.3037771600974431}. Best is trial 16 with value: 35.2599739402343.
[I 2026-01-25 14:46:24,022] Trial 17 finished with value: 40.30979773478312 and parameters: {'n_estimators': 588, 'learning_rate': 0.0006445392781213823, 'max_depth': 6, 'min_child_weight': 4.129012378419905, 'subsample': 0.9287468241582425, 'colsample_bytree': 0.8556985621107104, 'gamma': 0.6572909984725753, 'reg_alpha': 1.6349816737857794, 'reg_lambda': 0.33795262683418087}. Best is trial 16 with value: 35.2599739402343.
[I 2026-01-25 14:46:31,764] Trial 18 finished with value: 35.32688459820919 and parameters: {'n_estimators': 572, 'learning_rate': 0.0038170203681481924, 'max_depth': 5, 'min_child_weight': 3.7850416436124985, 'subsample': 0.9962975020392384, 'colsample_bytree': 0.7190682305009901, 'gamma': 0.08316467387877896, 'reg_alpha': 2.259215785730001, 'reg_lambda': 0.2025829675425125}. Best is trial 16 with value: 35.2599739402343.
[I 2026-01-25 14:46:37,786] Trial 19 finished with value: 42.963777931144 and parameters: {'n_estimators': 174, 'learning_rate': 0.0007425772322995167, 'max_depth': 8, 'min_child_weight': 11.948768790912645, 'subsample': 0.9190871711678865, 'colsample_bytree': 0.8693370381887338, 'gamma': 0.9757156710619026, 'reg_alpha': 1.217704100817783, 'reg_lambda': 0.4519559763420136}. Best is trial 16 with value: 35.2599739402343.
[I 2026-01-25 14:46:47,648] Trial 20 finished with value: 35.29849670753809 and parameters: {'n_estimators': 683, 'learning_rate': 0.0036158684542087855, 'max_depth': 6, 'min_child_weight': 2.8953476455802862, 'subsample': 0.8552914494152242, 'colsample_bytree': 0.7883569736099363, 'gamma': 2.036693150810921, 'reg_alpha': 2.7600096498611553, 'reg_lambda': 1.0325420243017807}. Best is trial 16 with value: 35.2599739402343.
[I 2026-01-25 14:46:59,235] Trial 21 finished with value: 35.21837995358682 and parameters: {'n_estimators': 1475, 'learning_rate': 0.003992764105745345, 'max_depth': 7, 'min_child_weight': 10.201404641547652, 'subsample': 0.9348546952543572, 'colsample_bytree': 0.7876344920872262, 'gamma': 1.8655476751808047, 'reg_alpha': 1.2537947864451597, 'reg_lambda': 0.8327256068728531}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:47:14,445] Trial 22 finished with value: 35.36859370411643 and parameters: {'n_estimators': 1429, 'learning_rate': 0.003792335562981023, 'max_depth': 7, 'min_child_weight': 5.116206322103178, 'subsample': 0.9421316019167868, 'colsample_bytree': 0.7299267967508702, 'gamma': 0.8314761235524257, 'reg_alpha': 1.1382095554085556, 'reg_lambda': 0.404933214030684}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:47:39,098] Trial 23 finished with value: 35.55399088753955 and parameters: {'n_estimators': 1808, 'learning_rate': 0.001018063875943216, 'max_depth': 6, 'min_child_weight': 10.414307208240448, 'subsample': 0.9533119457981674, 'colsample_bytree': 0.8082500989430539, 'gamma': 1.384505754279222, 'reg_alpha': 1.5074381988757855, 'reg_lambda': 2.979343957123035}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:47:56,474] Trial 24 finished with value: 35.392588213865686 and parameters: {'n_estimators': 1189, 'learning_rate': 0.002746619467475719, 'max_depth': 7, 'min_child_weight': 14.556082962346219, 'subsample': 0.8924301331772628, 'colsample_bytree': 0.813499430304607, 'gamma': 0.4547572167757958, 'reg_alpha': 2.2324516238701335, 'reg_lambda': 0.968078273757573}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:48:07,402] Trial 25 finished with value: 44.61327456819852 and parameters: {'n_estimators': 916, 'learning_rate': 1.7533738256706625e-05, 'max_depth': 5, 'min_child_weight': 6.735218932096582, 'subsample': 0.8327284029113156, 'colsample_bytree': 0.7450361742764361, 'gamma': 3.1958679565198658, 'reg_alpha': 0.9843915011813048, 'reg_lambda': 0.19403549477562917}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:48:15,166] Trial 26 finished with value: 35.79818203280984 and parameters: {'n_estimators': 374, 'learning_rate': 0.0046951178379331234, 'max_depth': 8, 'min_child_weight': 3.7072257943186124, 'subsample': 0.8934800183858489, 'colsample_bytree': 0.885926553275031, 'gamma': 2.2806809534451657, 'reg_alpha': 2.0450209075420824, 'reg_lambda': 0.5077894087602312}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:48:27,006] Trial 27 finished with value: 35.849573086300026 and parameters: {'n_estimators': 1441, 'learning_rate': 0.0012384849240544657, 'max_depth': 4, 'min_child_weight': 5.565083409333441, 'subsample': 0.9940606612086967, 'colsample_bytree': 0.8397230560790933, 'gamma': 1.1009925982548496, 'reg_alpha': 1.435585964447522, 'reg_lambda': 9.158038697883066}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:49:08,161] Trial 28 finished with value: 36.45791128290836 and parameters: {'n_estimators': 1933, 'learning_rate': 0.000671263200912093, 'max_depth': 9, 'min_child_weight': 8.809396761068342, 'subsample': 0.9354347464109026, 'colsample_bytree': 0.7894365567243548, 'gamma': 2.784894575480002, 'reg_alpha': 0.003936085946915968, 'reg_lambda': 0.2876951543930583}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:49:15,572] Trial 29 finished with value: 35.39162389294752 and parameters: {'n_estimators': 1108, 'learning_rate': 0.005364259921123644, 'max_depth': 4, 'min_child_weight': 1.963459465071981, 'subsample': 0.9593300895524095, 'colsample_bytree': 0.6485654749818798, 'gamma': 1.751661233681673, 'reg_alpha': 3.353135332058078, 'reg_lambda': 0.14958175909149882}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:49:33,648] Trial 30 finished with value: 35.2983103694655 and parameters: {'n_estimators': 1673, 'learning_rate': 0.0026880830910744713, 'max_depth': 6, 'min_child_weight': 15.49479734104595, 'subsample': 0.8410556271959307, 'colsample_bytree': 0.9054870727928482, 'gamma': 0.34141394174090944, 'reg_alpha': 0.8926230676777416, 'reg_lambda': 0.9648609394115323}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:49:41,690] Trial 31 finished with value: 35.30565105970145 and parameters: {'n_estimators': 1526, 'learning_rate': 0.009969606596467426, 'max_depth': 9, 'min_child_weight': 9.072445991621535, 'subsample': 0.7131173579964629, 'colsample_bytree': 0.7765195141312233, 'gamma': 1.8664440303660255, 'reg_alpha': 0.49580661517160896, 'reg_lambda': 0.6609412210649933}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:49:51,438] Trial 32 finished with value: 35.43696770973175 and parameters: {'n_estimators': 1924, 'learning_rate': 0.0058804631806014295, 'max_depth': 7, 'min_child_weight': 7.796488399386453, 'subsample': 0.7811999766192644, 'colsample_bytree': 0.7203330953528149, 'gamma': 1.4682222115174262, 'reg_alpha': 0.34199707241638594, 'reg_lambda': 0.7437698038272581}. Best is trial 21 with value: 35.21837995358682.
[I 2026-01-25 14:49:58,078] Trial 33 finished with value: 35.137505215970045 and parameters: {'n_estimators': 1394, 'learning_rate': 0.006832601844816737, 'max_depth': 5, 'min_child_weight': 12.322856494494404, 'subsample': 0.9113274435388952, 'colsample_bytree': 0.7720759235243555, 'gamma': 2.1057209545760576, 'reg_alpha': 1.9076593853512231, 'reg_lambda': 1.1879319540901812}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:50:14,953] Trial 34 finished with value: 35.347910866676386 and parameters: {'n_estimators': 1347, 'learning_rate': 0.0016534249105411934, 'max_depth': 5, 'min_child_weight': 12.117232887445432, 'subsample': 0.9100107578001765, 'colsample_bytree': 0.8292427969628036, 'gamma': 0.7407746170272196, 'reg_alpha': 1.8740177875442676, 'reg_lambda': 1.2941192627854978}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:50:21,748] Trial 35 finished with value: 35.20524148045271 and parameters: {'n_estimators': 1034, 'learning_rate': 0.005906353847172258, 'max_depth': 4, 'min_child_weight': 15.636361345766332, 'subsample': 0.8853807422980045, 'colsample_bytree': 0.8022438859946412, 'gamma': 3.5303393561430845, 'reg_alpha': 2.2727703411480036, 'reg_lambda': 2.1442789048026785}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:50:28,804] Trial 36 finished with value: 35.278373857917074 and parameters: {'n_estimators': 981, 'learning_rate': 0.006266374582562019, 'max_depth': 4, 'min_child_weight': 15.04998549035452, 'subsample': 0.8793936915094257, 'colsample_bytree': 0.7443930936410336, 'gamma': 3.5949398966418555, 'reg_alpha': 2.4061148357224624, 'reg_lambda': 2.462295032027611}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:50:35,920] Trial 37 finished with value: 44.18707428654047 and parameters: {'n_estimators': 770, 'learning_rate': 6.590439251422216e-05, 'max_depth': 3, 'min_child_weight': 18.00507671435524, 'subsample': 0.8207345504869331, 'colsample_bytree': 0.7966823142359205, 'gamma': 3.4360848683206235, 'reg_alpha': 3.5473170964294827, 'reg_lambda': 4.880146847877849}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:50:41,969] Trial 38 finished with value: 35.2056183506259 and parameters: {'n_estimators': 453, 'learning_rate': 0.007151848469478819, 'max_depth': 5, 'min_child_weight': 3.2030885341008304, 'subsample': 0.90604474294102, 'colsample_bytree': 0.695236660447553, 'gamma': 2.2189437953113247, 'reg_alpha': 2.9340479598009948, 'reg_lambda': 1.684502837390907}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:50:47,265] Trial 39 finished with value: 35.824152814681675 and parameters: {'n_estimators': 1298, 'learning_rate': 0.006945772989408353, 'max_depth': 3, 'min_child_weight': 3.2535346273880554, 'subsample': 0.8856891566137782, 'colsample_bytree': 0.648040631419432, 'gamma': 4.194044706020336, 'reg_alpha': 3.1373192153202143, 'reg_lambda': 1.8254056651713488}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:50:52,082] Trial 40 finished with value: 36.916784907499036 and parameters: {'n_estimators': 387, 'learning_rate': 0.0029183506476364108, 'max_depth': 4, 'min_child_weight': 2.1205697406682087, 'subsample': 0.84833031141215, 'colsample_bytree': 0.6827386882410763, 'gamma': 2.147948691450714, 'reg_alpha': 3.826148909148283, 'reg_lambda': 2.3563864029697172}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:50:59,090] Trial 41 finished with value: 35.468576733010394 and parameters: {'n_estimators': 489, 'learning_rate': 0.00455160772826298, 'max_depth': 5, 'min_child_weight': 4.473467004451931, 'subsample': 0.9110747889122178, 'colsample_bytree': 0.7019757975188641, 'gamma': 2.7508995523505986, 'reg_alpha': 2.6531808134738095, 'reg_lambda': 1.4054694540665422}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:51:04,026] Trial 42 finished with value: 35.614058118454444 and parameters: {'n_estimators': 818, 'learning_rate': 0.008757594663856933, 'max_depth': 4, 'min_child_weight': 3.1632801217885116, 'subsample': 0.9173524750024393, 'colsample_bytree': 0.7666279739252708, 'gamma': 2.673611825076452, 'reg_alpha': 1.3692281184929136, 'reg_lambda': 1.6403033258651651}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:51:10,740] Trial 43 finished with value: 35.16001806406414 and parameters: {'n_estimators': 1032, 'learning_rate': 0.006897958264058851, 'max_depth': 5, 'min_child_weight': 2.626947459660896, 'subsample': 0.9685605358358402, 'colsample_bytree': 0.6580174204375657, 'gamma': 3.832728879943341, 'reg_alpha': 2.100193078623683, 'reg_lambda': 3.44273214946172}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:51:16,711] Trial 44 finished with value: 35.38441785247228 and parameters: {'n_estimators': 1031, 'learning_rate': 0.006607843829313127, 'max_depth': 5, 'min_child_weight': 2.457694674416289, 'subsample': 0.9666543491263501, 'colsample_bytree': 0.6254224036767856, 'gamma': 3.623728524107257, 'reg_alpha': 2.075001692388635, 'reg_lambda': 4.01137320501248}. Best is trial 33 with value: 35.137505215970045.
[I 2026-01-25 14:51:21,950] Trial 45 finished with value: 35.677635331411295 and parameters: {'n_estimators': 1076, 'learning_rate': 0.008160616074618841, 'max_depth': 4, 'min_child_weight': 1.1209961766950955, 'subsample': 0.9762812082121538, 'colsample_bytree': 0.6300570503362439, 'gamma': 4.017873287716568, 'reg_alpha': 2.9483989261527883, 'reg_lambda': 2.439397711895002}. Best is trial 33 with value: 35.137505215970045.

In [ ]:

# (Optional but recommended) restrict tuning to the years you actually plan to train on most of the time
df_tune = df_model.copy()

target_col = "yield_mean"

# 1) drop missing targets
df_tune = df_tune.dropna(subset=[target_col])

# 2) remove sentinel values if you use them (common in rasters)
df_tune = df_tune[df_tune[target_col] != -9999]   # add others if needed

# 3) enforce positive for log (choose one approach)
df_tune = df_tune[df_tune[target_col] > 0]        # strict (safest for log)

# optional sanity check
assert df_tune[target_col].isna().sum() == 0
assert (df_tune[target_col] <= 0).sum() == 0

rf_study, rf_best_params, rf_best_mae, rf_best_meta = tune_rf_optuna(
    df_tune, feature_cols, n_trials=50, n_splits=5
)
print("\nRF best params:", rf_best_params)
print("RF CV best MAE:", rf_best_mae)
print("RF CV meta:", rf_best_meta)

[I 2026-01-25 14:59:58,148] A new study created in memory with name: no-name-8e9242bb-a49d-4512-9315-4b9d4f25fd48

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-25 15:00:22,660] Trial 0 finished with value: 36.91717743057991 and parameters: {'n_estimators': 411, 'max_depth': 39, 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_features': 0.8, 'bootstrap': False}. Best is trial 0 with value: 36.91717743057991.
[I 2026-01-25 15:00:47,321] Trial 1 finished with value: 37.228817861018946 and parameters: {'n_estimators': 580, 'max_depth': 17, 'min_samples_split': 22, 'min_samples_leaf': 1, 'max_features': 0.8, 'bootstrap': True}. Best is trial 0 with value: 36.91717743057991.
[I 2026-01-25 15:00:53,638] Trial 2 finished with value: 35.355105852756864 and parameters: {'n_estimators': 287, 'max_depth': 3, 'min_samples_split': 23, 'min_samples_leaf': 10, 'max_features': 0.8, 'bootstrap': True}. Best is trial 2 with value: 35.355105852756864.
[I 2026-01-25 15:00:59,073] Trial 3 finished with value: 34.68761245157032 and parameters: {'n_estimators': 353, 'max_depth': 9, 'min_samples_split': 29, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 3 with value: 34.68761245157032.
[I 2026-01-25 15:01:06,202] Trial 4 finished with value: 36.62454265020396 and parameters: {'n_estimators': 365, 'max_depth': 2, 'min_samples_split': 28, 'min_samples_leaf': 14, 'max_features': 'log2', 'bootstrap': True}. Best is trial 3 with value: 34.68761245157032.
[I 2026-01-25 15:01:24,367] Trial 5 finished with value: 34.886059147928066 and parameters: {'n_estimators': 1040, 'max_depth': 34, 'min_samples_split': 7, 'min_samples_leaf': 13, 'max_features': 0.3, 'bootstrap': True}. Best is trial 3 with value: 34.68761245157032.
[I 2026-01-25 15:01:32,285] Trial 6 finished with value: 34.82501784689957 and parameters: {'n_estimators': 793, 'max_depth': 5, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}. Best is trial 3 with value: 34.68761245157032.
[I 2026-01-25 15:01:42,445] Trial 7 finished with value: 35.28458839045999 and parameters: {'n_estimators': 394, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': False}. Best is trial 3 with value: 34.68761245157032.
[I 2026-01-25 15:01:55,169] Trial 8 finished with value: 35.0859714003725 and parameters: {'n_estimators': 752, 'max_depth': 20, 'min_samples_split': 24, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 3 with value: 34.68761245157032.
[I 2026-01-25 15:02:14,144] Trial 9 finished with value: 34.95640830785322 and parameters: {'n_estimators': 1120, 'max_depth': 27, 'min_samples_split': 27, 'min_samples_leaf': 13, 'max_features': 0.3, 'bootstrap': True}. Best is trial 3 with value: 34.68761245157032.
[I 2026-01-25 15:02:32,460] Trial 10 finished with value: 34.60806822808517 and parameters: {'n_estimators': 1398, 'max_depth': 16, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 10 with value: 34.60806822808517.
[I 2026-01-25 15:02:49,850] Trial 11 finished with value: 34.63077799010653 and parameters: {'n_estimators': 1367, 'max_depth': 14, 'min_samples_split': 17, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 10 with value: 34.60806822808517.
[I 2026-01-25 15:03:06,978] Trial 12 finished with value: 34.670276250541335 and parameters: {'n_estimators': 1339, 'max_depth': 14, 'min_samples_split': 17, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 10 with value: 34.60806822808517.
[I 2026-01-25 15:03:24,939] Trial 13 finished with value: 34.73161657230071 and parameters: {'n_estimators': 1347, 'max_depth': 26, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 10 with value: 34.60806822808517.
[I 2026-01-25 15:03:39,057] Trial 14 finished with value: 34.70195646666918 and parameters: {'n_estimators': 1126, 'max_depth': 12, 'min_samples_split': 18, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 10 with value: 34.60806822808517.
[I 2026-01-25 15:04:22,995] Trial 15 finished with value: 35.88316864927709 and parameters: {'n_estimators': 1392, 'max_depth': 24, 'min_samples_split': 12, 'min_samples_leaf': 11, 'max_features': 0.5, 'bootstrap': False}. Best is trial 10 with value: 34.60806822808517.
[I 2026-01-25 15:04:37,195] Trial 16 finished with value: 35.257823818178295 and parameters: {'n_estimators': 951, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 10 with value: 34.60806822808517.
[I 2026-01-25 15:04:52,045] Trial 17 finished with value: 34.54563015733423 and parameters: {'n_estimators': 1239, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 17 with value: 34.54563015733423.
[I 2026-01-25 15:04:55,006] Trial 18 finished with value: 34.56838203201424 and parameters: {'n_estimators': 109, 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 17 with value: 34.54563015733423.
[I 2026-01-25 15:04:58,217] Trial 19 finished with value: 34.319229410794726 and parameters: {'n_estimators': 164, 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:05:09,428] Trial 20 finished with value: 34.47818411007093 and parameters: {'n_estimators': 888, 'max_depth': 22, 'min_samples_split': 25, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:05:17,534] Trial 21 finished with value: 34.50856713802322 and parameters: {'n_estimators': 613, 'max_depth': 21, 'min_samples_split': 25, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:05:25,411] Trial 22 finished with value: 34.50223692976508 and parameters: {'n_estimators': 578, 'max_depth': 22, 'min_samples_split': 25, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:05:36,387] Trial 23 finished with value: 34.42061910307969 and parameters: {'n_estimators': 915, 'max_depth': 30, 'min_samples_split': 26, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:05:47,393] Trial 24 finished with value: 34.47214670826912 and parameters: {'n_estimators': 883, 'max_depth': 31, 'min_samples_split': 30, 'min_samples_leaf': 13, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:05:57,973] Trial 25 finished with value: 34.43432377497293 and parameters: {'n_estimators': 870, 'max_depth': 31, 'min_samples_split': 29, 'min_samples_leaf': 13, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:06:00,895] Trial 26 finished with value: 34.47452266796416 and parameters: {'n_estimators': 111, 'max_depth': 31, 'min_samples_split': 27, 'min_samples_leaf': 14, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:06:09,606] Trial 27 finished with value: 34.51522116100853 and parameters: {'n_estimators': 668, 'max_depth': 39, 'min_samples_split': 21, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:06:21,173] Trial 28 finished with value: 34.5614986218588 and parameters: {'n_estimators': 956, 'max_depth': 35, 'min_samples_split': 30, 'min_samples_leaf': 14, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:06:28,337] Trial 29 finished with value: 34.97235251052663 and parameters: {'n_estimators': 469, 'max_depth': 36, 'min_samples_split': 27, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:06:46,787] Trial 30 finished with value: 35.291158141187964 and parameters: {'n_estimators': 825, 'max_depth': 30, 'min_samples_split': 19, 'min_samples_leaf': 11, 'max_features': 0.3, 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:06:57,828] Trial 31 finished with value: 34.47385456472777 and parameters: {'n_estimators': 901, 'max_depth': 30, 'min_samples_split': 30, 'min_samples_leaf': 13, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:07:06,760] Trial 32 finished with value: 34.42861093433154 and parameters: {'n_estimators': 687, 'max_depth': 32, 'min_samples_split': 28, 'min_samples_leaf': 14, 'max_features': 'log2', 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:07:40,545] Trial 33 finished with value: 36.92744734235701 and parameters: {'n_estimators': 697, 'max_depth': 37, 'min_samples_split': 22, 'min_samples_leaf': 14, 'max_features': 0.8, 'bootstrap': False}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:07:57,929] Trial 34 finished with value: 34.37439340211684 and parameters: {'n_estimators': 1038, 'max_depth': 28, 'min_samples_split': 23, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': True}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:08:10,175] Trial 35 finished with value: 35.94939110841853 and parameters: {'n_estimators': 282, 'max_depth': 26, 'min_samples_split': 23, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:08:27,787] Trial 36 finished with value: 34.37016186570527 and parameters: {'n_estimators': 1052, 'max_depth': 33, 'min_samples_split': 23, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': True}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:08:51,791] Trial 37 finished with value: 35.40831202533453 and parameters: {'n_estimators': 1057, 'max_depth': 39, 'min_samples_split': 14, 'min_samples_leaf': 15, 'max_features': 0.5, 'bootstrap': True}. Best is trial 19 with value: 34.319229410794726.
[I 2026-01-25 15:09:11,635] Trial 38 finished with value: 34.27632100542981 and parameters: {'n_estimators': 1195, 'max_depth': 28, 'min_samples_split': 22, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 38 with value: 34.27632100542981.
[I 2026-01-25 15:09:33,243] Trial 39 finished with value: 38.83619867054249 and parameters: {'n_estimators': 1223, 'max_depth': 1, 'min_samples_split': 22, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 38 with value: 34.27632100542981.
[I 2026-01-25 15:10:16,257] Trial 40 finished with value: 36.35879487667159 and parameters: {'n_estimators': 1213, 'max_depth': 19, 'min_samples_split': 23, 'min_samples_leaf': 9, 'max_features': 0.8, 'bootstrap': True}. Best is trial 38 with value: 34.27632100542981.
[I 2026-01-25 15:10:33,316] Trial 41 finished with value: 34.34287801286576 and parameters: {'n_estimators': 1022, 'max_depth': 28, 'min_samples_split': 24, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 38 with value: 34.27632100542981.
[I 2026-01-25 15:10:51,259] Trial 42 finished with value: 34.268613025078366 and parameters: {'n_estimators': 1070, 'max_depth': 27, 'min_samples_split': 21, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 42 with value: 34.268613025078366.
[I 2026-01-25 15:11:09,973] Trial 43 finished with value: 34.27758147174165 and parameters: {'n_estimators': 1130, 'max_depth': 28, 'min_samples_split': 20, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 42 with value: 34.268613025078366.
[I 2026-01-25 15:11:30,876] Trial 44 finished with value: 34.976379240365475 and parameters: {'n_estimators': 1272, 'max_depth': 24, 'min_samples_split': 20, 'min_samples_leaf': 11, 'max_features': 0.3, 'bootstrap': True}. Best is trial 42 with value: 34.268613025078366.
[I 2026-01-25 15:11:49,682] Trial 45 finished with value: 34.376149814301215 and parameters: {'n_estimators': 1136, 'max_depth': 28, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 42 with value: 34.268613025078366.
[I 2026-01-25 15:12:11,060] Trial 46 finished with value: 34.488808782514774 and parameters: {'n_estimators': 1291, 'max_depth': 24, 'min_samples_split': 21, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 42 with value: 34.268613025078366.

In [ ]:

if xgb_available:
    xgb_study, xgb_best_params, xgb_best_mae, xgb_best_meta = tune_xgb_optuna(
        df_tune, feature_cols, n_trials=60, n_splits=5
    )
    print("\nXGB best params:", xgb_best_params)
    print("XGB CV best MAE:", xgb_best_mae)
    print("XGB CV meta:", xgb_best_meta)