<a href="https://colab.research.google.com/github/samarranjit/Yield_Prediction/blob/main/30mresolution_data/TreeBasedModelsOn30mDatasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
corn_fn = r"/home/cholab/LabMembers/Samar/Yield_Prediction/data/monthlyTimeseriesData/2corn_monthly_timeseries_imputed_recalculated.parquet"

wheat_fn = r"/home/cholab/LabMembers/Samar/Yield_Prediction/data/monthlyTimeseriesData/2wheat_monthly_timeseries_imputed_recalculated.parquet"
soy_fn = r"/home/cholab/LabMembers/Samar/Yield_Prediction/data/monthlyTimeseriesData/2soybeans_monthly_timeseries_imputed_recalculated.parquet"
CROP = "wheat"   # "soy" | "corn" | "wheat"

fn_map = {"soy": soy_fn, "corn": corn_fn, "wheat": wheat_fn}
data_path = fn_map[CROP]

df = pd.read_parquet(data_path)
print("Loaded:", data_path)
print("Shape:", df.shape)
df.head()

Loaded: /home/cholab/LabMembers/Samar/Yield_Prediction/data/monthlyTimeseriesData/2wheat_monthly_timeseries_imputed_recalculated.parquet
Shape: (87660, 70)

,field,year,row,col,yield_mean,yield_std,yield_count,lon,lat,grid_crs,...,EVI,GI,NDWI,Tr_SWIR1,Tr_SWIR2,LST_K,PPT_mm,PPT_obsCount,HLS_obsCount,LST_obsCount
0,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.211280,2.230067,-0.093518,0.705636,1.389632,292.362000,68.996002,31.0,3.0,2.0
1,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.304914,2.919337,0.025263,1.014456,2.190767,292.362000,21.474001,28.0,6.0,2.0
2,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.380398,3.539373,0.118324,1.244815,2.836716,292.362000,89.545998,31.0,3.0,1.0
3,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.426225,3.676572,0.180334,1.349838,3.071973,305.155670,92.737999,30.0,1.0,1.0
4,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.440394,3.891422,0.172018,1.228205,2.787438,306.281921,172.608994,31.0,7.0,2.0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87660 entries, 0 to 87659
Data columns (total 70 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   field               87660 non-null  object
 1   year                87660 non-null  int64
 2   row                 87660 non-null  int64
 3   col                 87660 non-null  int64
 4   yield_mean          87660 non-null  float64
 5   yield_std           85930 non-null  float64
 6   yield_count         87660 non-null  int64
 7   lon                 87660 non-null  float64
 8   lat                 87660 non-null  float64
 9   grid_crs            87660 non-null  object
 10  template_raster     87660 non-null  object
 11  yield_meter_crs     87660 non-null  object
 12  LST_median          87660 non-null  float64
 13  LST_max             87660 non-null  float64
 14  LST_range           87660 non-null  float64
 15  NDVI_mean           87660 non-null  float64
 16  EVI_mean            87660 non-null  float64
 17  GI_mean             87660 non-null  float64
 18  NDWI_mean           87660 non-null  float64
 19  Tr_SWIR1_mean       87660 non-null  float64
 20  Tr_SWIR2_mean       87660 non-null  float64
 21  NDVI_max            87660 non-null  float64
 22  EVI_max             87660 non-null  float64
 23  GI_max              87660 non-null  float64
 24  NDWI_max            87660 non-null  float64
 25  Tr_SWIR1_max        87660 non-null  float64
 26  Tr_SWIR2_max        87660 non-null  float64
 27  NDVI_range          87660 non-null  float64
 28  EVI_range           87660 non-null  float64
 29  GI_range            87660 non-null  float64
 30  NDWI_range          87660 non-null  float64
 31  Tr_SWIR1_range      87660 non-null  float64
 32  Tr_SWIR2_range      87660 non-null  float64
 33  NDVI_obsCount       87660 non-null  float64
 34  ppt_mean            87660 non-null  float64
 35  ppt_max             87660 non-null  float64
 36  ppt_range           87660 non-null  float64
 37  ppt_total           87660 non-null  float64
 38  Soil_Sand           87660 non-null  float64
 39  Soil_Silt           87660 non-null  float64
 40  Soil_Clay           87660 non-null  float64
 41  Soil_BD             87660 non-null  float64
 42  Soil_pH             87660 non-null  float64
 43  Soil_OM             87660 non-null  float64
 44  Soil_Theta_S        87660 non-null  float64
 45  Soil_Theta_R        87660 non-null  float64
 46  Soil_Ksat           87660 non-null  float64
 47  Soil_Lambda         87660 non-null  float64
 48  Soil_Alpha          87660 non-null  float64
 49  Soil_N              87660 non-null  float64
 50  x_utm               87660 non-null  float64
 51  y_utm               87660 non-null  float64
 52  elevation           87660 non-null  float64
 53  slope               87660 non-null  float64
 54  aspect              87660 non-null  float64
 55  harvest_year        87660 non-null  int64
 56  season_year         87660 non-null  int64
 57  month               87660 non-null  int64
 58  season_month_index  87660 non-null  int64
 59  NDVI                87660 non-null  float64
 60  EVI                 87660 non-null  float64
 61  GI                  87660 non-null  float64
 62  NDWI                87660 non-null  float64
 63  Tr_SWIR1            87660 non-null  float64
 64  Tr_SWIR2            87660 non-null  float64
 65  LST_K               87660 non-null  float64
 66  PPT_mm              87660 non-null  float64
 67  PPT_obsCount        87660 non-null  float64
 68  HLS_obsCount        87660 non-null  float64
 69  LST_obsCount        87660 non-null  float64
dtypes: float64(58), int64(8), object(4)
memory usage: 46.8+ MB

In [33]:
df.rename(columns={"x_utm": "x_m", "y_utm": "y_m"}, inplace=True)
df.head()

,field,year,row,col,yield_mean,yield_std,yield_count,lon,lat,grid_crs,...,EVI,GI,NDWI,Tr_SWIR1,Tr_SWIR2,LST_K,PPT_mm,PPT_obsCount,HLS_obsCount,LST_obsCount
0,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.211280,2.230067,-0.093518,0.705636,1.389632,292.362000,68.996002,31.0,3.0,2.0
1,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.304914,2.919337,0.025263,1.014456,2.190767,292.362000,21.474001,28.0,6.0,2.0
2,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.380398,3.539373,0.118324,1.244815,2.836716,292.362000,89.545998,31.0,3.0,1.0
3,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.426225,3.676572,0.180334,1.349838,3.071973,305.155670,92.737999,30.0,1.0,1.0
4,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,EPSG:4326,...,0.440394,3.891422,0.172018,1.228205,2.787438,306.281921,172.608994,31.0,7.0,2.0

In [ ]:
# month_index      241080 non-null  int64
#  57  NDVI             241080 non-null  float64
#  58  EVI              241080 non-null  float64
#  59  GI               241080 non-null  float64
#  60  NDWI             241080 non-null  float64
#  61  Tr_SWIR1         241080 non-null  float64
#  62  Tr_SWIR2         241080 non-null  float64
#  63  LST_K            241080 non-null  float64
#  64  PPT_mm           241080 non-null  float64
#  65  PPT_obsCount     241080 non-null  float64
#  66  HLS_obsCount     241080 non-null  float64
#  67  LST_obsCount     241080 non-null  float64
#  68  window

In [40]:
df.drop(columns=[
    # "PPT_mm", "month",
    # "NDVI", "EVI", "GI", "NDWI", "LST_K", "Tr_SWIR1", "Tr_SWIR2", "PPT_obsCount", "HLS_obsCount", "LST_obsCount"
'grid_crs', 'template_raster', 'yield_meter_crs'
    ], inplace=True)
df.head()

,field,year,row,col,yield_mean,yield_std,yield_count,lon,lat,LST_median,...,Soil_Theta_R,Soil_Ksat,Soil_Lambda,Soil_Alpha,Soil_N,x_m,y_m,elevation,slope,aspect
0,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,291.331482,...,0.058628,0.134959,0.341773,-0.282014,1.370181,332403.946104,4.322064e+06,52.879803,3.701279,111.084793
1,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,291.331482,...,0.058628,0.134959,0.341773,-0.282014,1.370181,332403.946104,4.322064e+06,52.879803,3.701279,111.084793
2,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,291.331482,...,0.058628,0.134959,0.341773,-0.282014,1.370181,332403.946104,4.322064e+06,52.879803,3.701279,111.084793
3,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,291.331482,...,0.058628,0.134959,0.341773,-0.282014,1.370181,332403.946104,4.322064e+06,52.879803,3.701279,111.084793
4,North Farm_ND-1-B,2017,53,93,35.253355,2.538404,4,-76.936257,39.031575,291.331482,...,0.058628,0.134959,0.341773,-0.282014,1.370181,332403.946104,4.322064e+06,52.879803,3.701279,111.084793

In [41]:
df.keys()

Index(['field', 'year', 'row', 'col', 'yield_mean', 'yield_std', 'yield_count',
       'lon', 'lat', 'LST_median', 'LST_max', 'LST_range', 'NDVI_mean',
       'EVI_mean', 'GI_mean', 'NDWI_mean', 'Tr_SWIR1_mean', 'Tr_SWIR2_mean',
       'NDVI_max', 'EVI_max', 'GI_max', 'NDWI_max', 'Tr_SWIR1_max',
       'Tr_SWIR2_max', 'NDVI_range', 'EVI_range', 'GI_range', 'NDWI_range',
       'Tr_SWIR1_range', 'Tr_SWIR2_range', 'ppt_mean', 'ppt_max', 'ppt_range',
       'ppt_total', 'Soil_Sand', 'Soil_Silt', 'Soil_Clay', 'Soil_BD',
       'Soil_pH', 'Soil_OM', 'Soil_Theta_S', 'Soil_Theta_R', 'Soil_Ksat',
       'Soil_Lambda', 'Soil_Alpha', 'Soil_N', 'x_m', 'y_m', 'elevation',
       'slope', 'aspect'],
      dtype='object')

In [42]:
df_seasonal = (
    df
    .groupby(["x_m", "y_m", "year"], as_index=False)
    .mean(numeric_only=True)
)

print("Original rows:", len(df))
print("Seasonal pixel-year rows:", len(df_seasonal))

Original rows: 87660
Seasonal pixel-year rows: 8749

In [ ]:
df.keys()

Index(['field', 'year', 'row', 'col', 'yield_mean', 'yield_std', 'yield_count',
       'lon', 'lat', 'grid_crs', 'template_raster', 'yield_meter_crs',
       'LST_median', 'LST_max', 'LST_range', 'NDVI_mean', 'EVI_mean',
       'GI_mean', 'NDWI_mean', 'Tr_SWIR1_mean', 'Tr_SWIR2_mean', 'NDVI_max',
       'EVI_max', 'GI_max', 'NDWI_max', 'Tr_SWIR1_max', 'Tr_SWIR2_max',
       'NDVI_range', 'EVI_range', 'GI_range', 'NDWI_range', 'Tr_SWIR1_range',
       'Tr_SWIR2_range', 'NDVI_obsCount', 'ppt_mean', 'ppt_max', 'ppt_range',
       'ppt_total', 'Soil_Sand', 'Soil_Silt', 'Soil_Clay', 'Soil_BD',
       'Soil_pH', 'Soil_OM', 'Soil_Theta_S', 'Soil_Theta_R', 'Soil_Ksat',
       'Soil_Lambda', 'Soil_Alpha', 'Soil_N', 'x_m', 'y_m', 'elevation',
       'slope', 'aspect'],
      dtype='object')

In [43]:
df_model = df_seasonal.copy()
df_model.head()

,x_m,y_m,year,row,col,yield_mean,yield_std,yield_count,lon,lat,...,Soil_OM,Soil_Theta_S,Soil_Theta_R,Soil_Ksat,Soil_Lambda,Soil_Alpha,Soil_N,elevation,slope,aspect
0,332403.946104,4.322064e+06,2017,53.0,93.0,35.253355,2.538404,4.0,-76.936257,39.031575,...,-0.908014,0.425776,0.058628,0.134959,0.341773,-0.282014,1.370181,52.879803,3.701279,111.084793
1,332427.274521,4.322064e+06,2017,53.0,94.0,39.823887,3.597768,13.0,-76.935988,39.031575,...,-0.940171,0.430990,0.059809,0.126548,0.328477,-0.329472,1.356183,51.431164,2.618012,117.239586
2,332427.911213,4.322094e+06,2017,52.0,94.0,42.725662,2.709190,21.0,-76.935988,39.031844,...,-0.944601,0.435864,0.062402,0.125224,0.316242,-0.373594,1.340308,51.880959,2.491522,110.951508
3,332428.547908,4.322124e+06,2017,51.0,94.0,35.742679,0.358608,13.0,-76.935988,39.032114,...,-0.888167,0.429276,0.066825,0.021985,0.310395,-0.389892,1.328873,52.336819,2.405489,107.738846
4,332429.184607,4.322153e+06,2017,50.0,94.0,36.732437,1.076467,2.0,-76.935988,39.032383,...,-0.882307,0.428713,0.063118,0.122812,0.318603,-0.373196,1.341801,52.818752,2.655015,110.727654

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

try:
    from xgboost import XGBRegressor
    xgb_available = True
except Exception as e:
    xgb_available = False
    print("XGBoost not available:", e)

YEAR_COL   = "year"
TARGET_RAW = "yield_mean"
FIXED_VAL_YEARS = [2022, 2015, 2016]

# Ensure log target exists
if "y_log" not in df_model.columns:
    df_model = df_model.copy()
    df_model["y_log"] = np.log1p(df_model[TARGET_RAW].astype(float))

# Features: numeric only, drop obvious non-features
drop_cols = {TARGET_RAW, "y_log", YEAR_COL, "row", "col", "lat", "lon"}
feature_cols = [c for c in df_model.columns
                if c not in drop_cols and pd.api.types.is_numeric_dtype(df_model[c])]

print("Num features:", len(feature_cols))

Num features: 44

In [ ]:
RF best params: {'n_estimators': 161, 'max_depth': 1, 'min_samples_split': 16, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}

In [26]:
import numpy as np
import xgboost as xgb

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


def build_preprocessor(feature_cols):
    # Fit on train only (Pipeline handles this correctly)
    num_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])
    return ColumnTransformer([("num", num_pipe, feature_cols)], remainder="drop")


def make_rf_pipeline(feature_cols):
    pre = build_preprocessor(feature_cols)

    rf = RandomForestRegressor(
        n_estimators=161,
        max_depth=1,
        min_samples_split=16,
        min_samples_leaf=15,
        max_features=0.8,
        bootstrap=True
    )

    return Pipeline([("pre", pre), ("model", rf)])

    #XGB best params: {'n_estimators': 1629, 'learning_rate': 0.004670767807091202, 'max_depth': 5, 'min_child_weight': 4.819600424745501, 'subsample': 0.810291624136574, 'colsample_bytree': 0.6859053703386455, 'gamma': 1.0873018635007852, 'reg_alpha': 4.264641635924872, 'reg_lambda': 2.5028009562399314}
# {'n_estimators': 2159, 'learning_rate': 0.0031914430639582696, 'max_depth': 6, 'min_child_weight': 14.311447050028924, 'subsample': 0.7659272067418138, 'colsample_bytree': 0.9474638752529032, 'gamma': 1.467417425111204, 'reg_alpha': 1.9492126518340904, 'reg_lambda': 1.5715351921165521}
# XGB best params: {'n_estimators': 2039, 'learning_rate': 0.0020104754290378385, 'max_depth': 10, 'min_child_weight': 6.304348883791848, 'subsample': 0.6653297650398029, 'colsample_bytree': 0.6263706543395052, 'gamma': 0.338389078154123, 'reg_alpha': 0.3839632496251091, 'reg_lambda': 4.671144007141974}
def make_xgb_pipeline(feature_cols):
    pre = build_preprocessor(feature_cols)

    xgb_model = XGBRegressor(
        n_estimators=2050,
        learning_rate=0.0020104754290378385,
        random_state=42,
        n_jobs=-1,


        max_depth= 10,
        min_child_weight= 14.311447050028924,
        subsample = 0.7659272067418138,
        colsample_bytree = 0.9474638752529032,
        gamma = 1.467417425111204,
        reg_alpha= 1.9492126518340904,
        reg_lambda=  1.5715351921165521,

        # ✅ GPU
        tree_method="hist",
        device="cuda",
    )
    return Pipeline([("pre", pre), ("model", xgb_model)])


def corr_sq_raw(y_true_raw, y_pred_raw):
    y_true_raw = np.asarray(y_true_raw, dtype=float)
    y_pred_raw = np.asarray(y_pred_raw, dtype=float)
    if np.std(y_true_raw) == 0 or np.std(y_pred_raw) == 0:
        return np.nan
    r = np.corrcoef(y_true_raw, y_pred_raw)[0, 1]
    return float(r * r)


def eval_raw_metrics_from_log_model(pipe, X, y_true_raw):
    """
    pipe predicts log1p(y). We inverse-transform with expm1 and compute metrics in RAW space.
    """
    yhat_log = pipe.predict(X)
    yhat_raw = np.expm1(yhat_log)

    mae = float(mean_absolute_error(y_true_raw, yhat_raw))               # ✅ raw units
    rmse = float(np.sqrt(mean_squared_error(y_true_raw, yhat_raw)))     # ✅ raw units
    r2 = float(r2_score(y_true_raw, yhat_raw))                           # ✅ raw space
    c2 = float(corr_sq_raw(y_true_raw, yhat_raw))                        # ✅ raw space

    return {"mae": mae, "rmse": rmse, "r2": r2, "corr2": c2}


def get_splits(df, test_year):
    all_years = sorted(df[YEAR_COL].unique())

    val_years_used = [y for y in FIXED_VAL_YEARS if y != test_year]
    train_years = [y for y in all_years if (y != test_year and y not in val_years_used)]

    train_df = df[df[YEAR_COL].isin(train_years)].copy()
    val_df = df[df[YEAR_COL].isin(val_years_used)].copy()
    test_df = df[df[YEAR_COL] == test_year].copy()
    return train_df, val_df, test_df, val_years_used


def compute_split_metrics(pipe, X, y_log, y_raw):
    """
    pipe is trained on log targets. This returns metrics on RAW space after expm1.
    """
    yhat_log = pipe.predict(X)
    yhat_raw = np.expm1(yhat_log)

    out = {
        "mae": float(mean_absolute_error(y_raw, yhat_raw)),
        "rmse": float(np.sqrt(mean_squared_error(y_raw, yhat_raw))),
        "r2": float(r2_score(y_raw, yhat_raw)),
        "corr2": float(corr_sq_raw(y_raw, yhat_raw)),
    }
    return out


# ============================================================
# ✅ ADDITION: XGBoost early stopping + GPU (version-safe)
# ============================================================

def fit_xgb_pipeline_with_early_stopping(
    pipe,
    X_train, y_train_log,
    X_val, y_val_log,
    early_stopping_rounds=50
):
    """
    Fit XGBoost with early stopping using native xgb.train,
    mirroring the tuning-time implementation exactly.
    """

    pre = pipe.named_steps["pre"]
    model = pipe.named_steps["model"]

    # preprocess
    X_tr_t = pre.fit_transform(X_train)
    X_va_t = pre.transform(X_val)

    # DMatrix
    dtrain = xgb.DMatrix(X_tr_t, label=y_train_log)
    dvalid = xgb.DMatrix(X_va_t, label=y_val_log)


    # native xgb params (same as tuning)
    xgb_params = {
        "objective": "reg:squarederror",
        "eval_metric": "rmse",
        "seed": model.random_state,

        # ✅ GPU
        "tree_method": "hist",
        "device": "cuda",

        # hyperparameters
        "eta": model.learning_rate,
        "max_depth": int(model.max_depth),
        "subsample": float(model.subsample),
        "colsample_bytree": float(model.colsample_bytree),
        "lambda": float(model.reg_lambda),
    }

    booster = xgb.train(
        params=xgb_params,
        dtrain=dtrain,
        num_boost_round=model.n_estimators,
        evals=[(dvalid, "valid")],
        early_stopping_rounds=early_stopping_rounds,
        verbose_eval=False
    )

    return booster, pre

In [45]:
def plot_learning_curve_fold(make_pipe_fn, train_df, val_df, title,
                             train_fracs=(0.1, 0.2, 0.4, 0.6, 0.8, 1.0),
                             seed=42):

    rng = np.random.default_rng(seed)

    # Keep as DataFrames
    X_val = val_df[feature_cols]
    y_val_raw = val_df[TARGET_RAW].values

    n = len(train_df)
    sizes = [max(200, int(n*f)) for f in train_fracs]  # ensure not too tiny
    sizes = sorted(set([min(s, n) for s in sizes]))

    train_mae, val_mae = [], []

    for s in sizes:
        # subsample train
        idx = rng.choice(n, size=s, replace=False)
        sub = train_df.iloc[idx]

        X_tr = sub[feature_cols]
        y_tr_log = sub["y_log"].values
        y_tr_raw = sub[TARGET_RAW].values

        pipe = make_pipe_fn(feature_cols)
        pipe.fit(X_tr, y_tr_log)

        m_tr = compute_split_metrics(pipe, X_tr, y_tr_log, y_tr_raw)["mae"]
        m_va = compute_split_metrics(pipe, X_val, val_df["y_log"].values, y_val_raw)["mae"]

        train_mae.append(m_tr)
        val_mae.append(m_va)

    plt.figure()
    plt.plot(sizes, train_mae, marker="o", label="Train MAE (raw)")
    plt.plot(sizes, val_mae, marker="o", label="Val MAE (raw)")
    plt.xlabel("Training samples")
    plt.ylabel("MAE (raw yield units)")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.show()

## Corn Loyo Results

In [30]:
rows = []
all_years = sorted(df_model["year"].unique())

for test_year in all_years:
    train_df, val_df, test_df, val_years_used = get_splits(df_model, test_year)

    # --- MINIMAL NA FIX (target only) ---
    train_df = train_df[np.isfinite(train_df["y_log"])]
    val_df   = val_df[np.isfinite(val_df["y_log"])]
    test_df  = test_df[np.isfinite(test_df["y_log"])]

    # DataFrames for X, raw targets for metrics
    X_train = train_df[feature_cols]
    y_train_raw = train_df[TARGET_RAW].values

    X_val = val_df[feature_cols]
    y_val_raw = val_df[TARGET_RAW].values

    X_test = test_df[feature_cols]
    y_test_raw = test_df[TARGET_RAW].values



    # ---------------- RF ----------------
    rf_pipe = make_rf_pipeline(feature_cols)
    rf_pipe.fit(X_train, train_df["y_log"].values)  # training target in log space

    rf_train = eval_raw_metrics_from_log_model(rf_pipe, X_train, y_train_raw)
    rf_val   = eval_raw_metrics_from_log_model(rf_pipe, X_val,   y_val_raw)  if len(val_df) else {"mae":np.nan,"rmse":np.nan,"r2":np.nan,"corr2":np.nan}
    rf_test  = eval_raw_metrics_from_log_model(rf_pipe, X_test,  y_test_raw)

    rows.append({
        "test_year": int(test_year),
        "model": "RF",
        "val_years_used": ",".join(map(str, val_years_used)),
        "train_size": int(len(train_df)),
        "val_size": int(len(val_df)),
        "test_size": int(len(test_df)),
        "train_mae": rf_train["mae"], "train_rmse": rf_train["rmse"], "train_r2": rf_train["r2"], "train_corr2": rf_train["corr2"],
        "val_mae":   rf_val["mae"],   "val_rmse":   rf_val["rmse"],   "val_r2":   rf_val["r2"],   "val_corr2":   rf_val["corr2"],
        "test_mae":  rf_test["mae"],  "test_rmse":  rf_test["rmse"],  "test_r2":  rf_test["r2"],  "test_corr2":  rf_test["corr2"],
    })

    print(f"\n=== {test_year} | RF | ValYears={val_years_used} ===")
    print(f"Train: MAE={rf_train['mae']:.3f} RMSE={rf_train['rmse']:.3f} R2={rf_train['r2']:.3f} Corr^2={rf_train['corr2']:.3f}")
    print(f"Val  : MAE={rf_val['mae']:.3f} RMSE={rf_val['rmse']:.3f} R2={rf_val['r2']:.3f} Corr^2={rf_val['corr2']:.3f}")
    print(f"Test : MAE={rf_test['mae']:.3f} RMSE={rf_test['rmse']:.3f} R2={rf_test['r2']:.3f} Corr^2={rf_test['corr2']:.3f}")

    # ---------------- XGB ----------------
    if xgb_available:
        xgb_pipe = make_xgb_pipeline(feature_cols)

        # ✅ EARLY STOPPING + GPU (same as tuning)
        booster, pre = fit_xgb_pipeline_with_early_stopping(
            xgb_pipe,
            X_train, train_df["y_log"].values,
            X_val,   val_df["y_log"].values,
            early_stopping_rounds=50
        )

        # --- predict TRAIN ---
        X_train_t = pre.transform(X_train)
        dtrain = xgb.DMatrix(X_train_t)
        yhat_train_log = booster.predict(dtrain)
        xgb_train = eval_raw_metrics_from_log_preds(y_train_raw, yhat_train_log)

        # --- predict VAL ---
        if len(val_df):
            X_val_t = pre.transform(X_val)
            dval = xgb.DMatrix(X_val_t)
            yhat_val_log = booster.predict(dval)
            xgb_val = eval_raw_metrics_from_log_preds(y_val_raw, yhat_val_log)
        else:
            xgb_val = {"mae":np.nan,"rmse":np.nan,"r2":np.nan,"corr2":np.nan}

        # --- predict TEST ---
        X_test_t = pre.transform(X_test)
        dtest = xgb.DMatrix(X_test_t)
        yhat_test_log = booster.predict(dtest)
        xgb_test = eval_raw_metrics_from_log_preds(y_test_raw, yhat_test_log)

        rows.append({
            "test_year": int(test_year),
            "model": "XGB",
            "val_years_used": ",".join(map(str, val_years_used)),
            "train_size": int(len(train_df)),
            "val_size": int(len(val_df)),
            "test_size": int(len(test_df)),
            "train_mae": xgb_train["mae"], "train_rmse": xgb_train["rmse"], "train_r2": xgb_train["r2"], "train_corr2": xgb_train["corr2"],
            "val_mae":   xgb_val["mae"],   "val_rmse":   xgb_val["rmse"],   "val_r2":   xgb_val["r2"],   "val_corr2":   xgb_val["corr2"],
            "test_mae":  xgb_test["mae"],  "test_rmse":  xgb_test["rmse"],  "test_r2":  xgb_test["r2"],  "test_corr2":  xgb_test["corr2"],
        })

        print(f"\n=== {test_year} | XGB | ValYears={val_years_used} ===")
        print(f"Train: MAE={xgb_train['mae']:.3f} RMSE={xgb_train['rmse']:.3f} R2={xgb_train['r2']:.3f} Corr^2={xgb_train['corr2']:.3f}")
        print(f"Val  : MAE={xgb_val['mae']:.3f} RMSE={xgb_val['rmse']:.3f} R2={xgb_val['r2']:.3f} Corr^2={xgb_val['corr2']:.3f}")
        print(f"Test : MAE={xgb_test['mae']:.3f} RMSE={xgb_test['rmse']:.3f} R2={xgb_test['r2']:.3f} Corr^2={xgb_test['corr2']:.3f}")

res_all = pd.DataFrame(rows).sort_values(["model", "test_year"]).reset_index(drop=True)
res_all

=== 2014 | RF | ValYears=[2023, 2019, 2024] ===
Train: MAE=16.954 RMSE=22.525 R2=0.814 Corr^2=0.835
Val  : MAE=31.355 RMSE=39.177 R2=0.409 Corr^2=0.433
Test : MAE=39.169 RMSE=45.134 R2=-0.825 Corr^2=0.208

=== 2014 | XGB | ValYears=[2023, 2019, 2024] ===
Train: MAE=15.829 RMSE=20.829 R2=0.841 Corr^2=0.851
Val  : MAE=31.140 RMSE=39.932 R2=0.386 Corr^2=0.391
Test : MAE=44.032 RMSE=51.018 R2=-1.332 Corr^2=0.327

=== 2015 | RF | ValYears=[2023, 2019, 2024] ===
Train: MAE=16.424 RMSE=21.782 R2=0.811 Corr^2=0.833
Val  : MAE=30.893 RMSE=38.780 R2=0.421 Corr^2=0.431
Test : MAE=24.587 RMSE=31.537 R2=0.527 Corr^2=0.559

=== 2015 | XGB | ValYears=[2023, 2019, 2024] ===
Train: MAE=15.878 RMSE=21.050 R2=0.823 Corr^2=0.835
Val  : MAE=32.989 RMSE=42.353 R2=0.309 Corr^2=0.330
Test : MAE=27.647 RMSE=35.321 R2=0.407 Corr^2=0.482

=== 2016 | RF | ValYears=[2023, 2019, 2024] ===
Train: MAE=16.812 RMSE=22.265 R2=0.812 Corr^2=0.834
Val  : MAE=30.921 RMSE=38.783 R2=0.421 Corr^2=0.422
Test : MAE=37.329 RMSE=44.141 R2=0.016 Corr^2=0.372

=== 2016 | XGB | ValYears=[2023, 2019, 2024] ===
Train: MAE=20.182 RMSE=25.991 R2=0.744 Corr^2=0.781
Val  : MAE=32.293 RMSE=40.663 R2=0.363 Corr^2=0.366
Test : MAE=38.966 RMSE=46.289 R2=-0.082 Corr^2=0.317

=== 2017 | RF | ValYears=[2023, 2019, 2024] ===
Train: MAE=16.449 RMSE=21.778 R2=0.819 Corr^2=0.838
Val  : MAE=33.525 RMSE=41.617 R2=0.333 Corr^2=0.414
Test : MAE=30.684 RMSE=38.978 R2=0.335 Corr^2=0.407

=== 2017 | XGB | ValYears=[2023, 2019, 2024] ===
Train: MAE=15.034 RMSE=19.790 R2=0.850 Corr^2=0.860
Val  : MAE=32.728 RMSE=41.557 R2=0.335 Corr^2=0.382
Test : MAE=29.588 RMSE=37.014 R2=0.400 Corr^2=0.485

=== 2018 | RF | ValYears=[2023, 2019, 2024] ===
Train: MAE=16.783 RMSE=22.173 R2=0.807 Corr^2=0.829
Val  : MAE=31.146 RMSE=38.990 R2=0.415 Corr^2=0.433
Test : MAE=24.485 RMSE=30.236 R2=0.191 Corr^2=0.526

=== 2018 | XGB | ValYears=[2023, 2019, 2024] ===
Train: MAE=15.630 RMSE=20.514 R2=0.835 Corr^2=0.845
Val  : MAE=31.576 RMSE=40.393 R2=0.372 Corr^2=0.378
Test : MAE=26.631 RMSE=33.666 R2=-0.003 Corr^2=0.454

=== 2019 | RF | ValYears=[2023, 2024] ===
Train: MAE=16.537 RMSE=21.972 R2=0.814 Corr^2=0.835
Val  : MAE=30.735 RMSE=39.076 R2=0.525 Corr^2=0.535
Test : MAE=31.880 RMSE=39.031 R2=0.058 Corr^2=0.228

=== 2019 | XGB | ValYears=[2023, 2024] ===
Train: MAE=20.110 RMSE=25.898 R2=0.742 Corr^2=0.773
Val  : MAE=34.661 RMSE=44.334 R2=0.389 Corr^2=0.390
Test : MAE=28.889 RMSE=35.239 R2=0.232 Corr^2=0.288

=== 2020 | RF | ValYears=[2023, 2019, 2024] ===
Train: MAE=15.964 RMSE=21.211 R2=0.823 Corr^2=0.843
Val  : MAE=31.461 RMSE=39.245 R2=0.407 Corr^2=0.424
Test : MAE=39.317 RMSE=49.230 R2=0.151 Corr^2=0.398

=== 2020 | XGB | ValYears=[2023, 2019, 2024] ===
Train: MAE=14.796 RMSE=19.605 R2=0.849 Corr^2=0.858
Val  : MAE=32.604 RMSE=41.409 R2=0.340 Corr^2=0.344
Test : MAE=41.346 RMSE=52.333 R2=0.040 Corr^2=0.398

=== 2021 | RF | ValYears=[2023, 2019, 2024] ===
Train: MAE=16.187 RMSE=21.696 R2=0.818 Corr^2=0.838
Val  : MAE=30.749 RMSE=38.352 R2=0.434 Corr^2=0.448
Test : MAE=41.954 RMSE=49.307 R2=-0.019 Corr^2=0.388

=== 2021 | XGB | ValYears=[2023, 2019, 2024] ===
Train: MAE=16.264 RMSE=21.336 R2=0.824 Corr^2=0.838
Val  : MAE=32.482 RMSE=40.714 R2=0.362 Corr^2=0.370
Test : MAE=39.451 RMSE=47.028 R2=0.073 Corr^2=0.369

=== 2022 | RF | ValYears=[2023, 2019, 2024] ===
Train: MAE=16.224 RMSE=21.631 R2=0.816 Corr^2=0.837
Val  : MAE=30.405 RMSE=38.493 R2=0.430 Corr^2=0.456
Test : MAE=39.459 RMSE=50.208 R2=0.126 Corr^2=0.418

=== 2022 | XGB | ValYears=[2023, 2019, 2024] ===
Train: MAE=22.674 RMSE=28.587 R2=0.679 Corr^2=0.750
Val  : MAE=33.124 RMSE=42.197 R2=0.314 Corr^2=0.374
Test : MAE=40.015 RMSE=49.787 R2=0.141 Corr^2=0.433

=== 2023 | RF | ValYears=[2019, 2024] ===
Train: MAE=16.575 RMSE=22.007 R2=0.814 Corr^2=0.835
Val  : MAE=30.239 RMSE=37.890 R2=0.137 Corr^2=0.317
Test : MAE=32.950 RMSE=41.143 R2=0.319 Corr^2=0.345

=== 2023 | XGB | ValYears=[2019, 2024] ===
Train: MAE=15.777 RMSE=20.820 R2=0.833 Corr^2=0.843
Val  : MAE=28.184 RMSE=35.154 R2=0.257 Corr^2=0.339
Test : MAE=38.078 RMSE=48.838 R2=0.040 Corr^2=0.275

=== 2024 | RF | ValYears=[2023, 2019] ===
Train: MAE=16.559 RMSE=21.991 R2=0.814 Corr^2=0.835
Val  : MAE=32.169 RMSE=39.859 R2=0.340 Corr^2=0.349
Test : MAE=27.458 RMSE=35.745 R2=-0.426 Corr^2=0.176

=== 2024 | XGB | ValYears=[2023, 2019] ===
Train: MAE=20.888 RMSE=26.773 R2=0.724 Corr^2=0.762
Val  : MAE=33.078 RMSE=41.531 R2=0.284 Corr^2=0.297
Test : MAE=30.105 RMSE=38.574 R2=-0.661 Corr^2=0.171

,test_year,model,val_years_used,train_size,val_size,test_size,train_mae,train_rmse,train_r2,train_corr2,val_mae,val_rmse,val_r2,val_corr2,test_mae,test_rmse,test_r2,test_corr2
0,2014,RF,"2023,2019,2024",11572,4831,1064,16.954154,22.525200,0.814164,0.834561,31.354777,39.176752,0.409075,0.432833,39.169262,45.133881,-0.825015,0.207700
1,2015,RF,"2023,2019,2024",10986,4831,1650,16.423527,21.782404,0.810862,0.833390,30.892595,38.780075,0.420981,0.431173,24.587344,31.537212,0.526969,0.559471
2,2016,RF,"2023,2019,2024",10371,4831,2265,16.812334,22.265103,0.811997,0.834263,30.921122,38.783345,0.420883,0.421797,37.328606,44.141455,0.016278,0.371933
3,2017,RF,"2023,2019,2024",11232,4831,1404,16.449368,21.778079,0.818598,0.838470,33.525303,41.616674,0.333178,0.413576,30.684139,38.978074,0.334617,0.407153
4,2018,RF,"2023,2019,2024",11903,4831,733,16.783399,22.173386,0.806856,0.829213,31.145975,38.989762,0.414703,0.433132,24.484969,30.236184,0.191194,0.526397
5,2019,RF,"2023,2024",12636,2889,1942,16.536846,21.972339,0.814130,0.835322,30.735011,39.076017,0.525433,0.534755,31.879697,39.030829,0.058028,0.227955
6,2020,RF,"2023,2019,2024",10868,4831,1768,15.963876,21.211150,0.822998,0.842605,31.461411,39.245143,0.407010,0.424086,39.317292,49.229974,0.150861,0.397770
7,2021,RF,"2023,2019,2024",10107,4831,2529,16.186605,21.695947,0.818306,0.838169,30.748580,38.352010,0.433693,0.448036,41.954306,49.307387,-0.019047,0.387740
8,2022,RF,"2023,2019,2024",11413,4831,1223,16.224259,21.631024,0.816285,0.836567,30.405003,38.493072,0.429520,0.455987,39.459483,50.208126,0.126329,0.418241
9,2023,RF,"2019,2024",12636,3055,1776,16.574853,22.007142,0.813541,0.834771,30.239220,37.890110,0.136953,0.316525,32.949693,41.143148,0.318726,0.345432
10,2024,RF,"2023,2019",12636,3718,1113,16.559446,21.990581,0.813821,0.834902,32.168941,39.858800,0.340172,0.349483,27.457673,35.744664,-0.426027,0.175979
11,2014,XGB,"2023,2019,2024",11572,4831,1064,15.829482,20.828899,0.841099,0.850719,31.139983,39.931599,0.386084,0.390927,44.031564,51.018074,-1.331897,0.326949
12,2015,XGB,"2023,2019,2024",10986,4831,1650,15.877508,21.049643,0.823373,0.834635,32.988753,42.352802,0.309379,0.329590,27.646822,35.321431,0.406638,0.482209
13,2016,XGB,"2023,2019,2024",10371,4831,2265,20.181716,25.991456,0.743802,0.780591,32.293410,40.662588,0.363402,0.366216,38.966065,46.289184,-0.081778,0.317365
14,2017,XGB,"2023,2019,2024",11232,4831,1404,15.033553,19.790449,0.850199,0.859590,32.728490,41.557475,0.335073,0.381849,29.587794,37.013645,0.399996,0.484724
15,2018,XGB,"2023,2019,2024",11903,4831,733,15.629621,20.514109,0.834681,0.844512,31.575622,40.393363,0.371804,0.377899,26.631179,33.666156,-0.002715,0.454115
16,2019,XGB,"2023,2024",12636,2889,1942,20.109677,25.897620,0.741788,0.772507,34.660856,44.334145,0.389123,0.390064,28.889431,35.238542,0.232182,0.288374
17,2020,XGB,"2023,2019,2024",10868,4831,1768,14.795802,19.605171,0.848786,0.858004,32.604124,41.408526,0.339831,0.344488,41.346304,52.332727,0.040453,0.397611
18,2021,XGB,"2023,2019,2024",10107,4831,2529,16.263988,21.335624,0.824291,0.837613,32.482157,40.714237,0.361783,0.369694,39.450810,47.027870,0.072998,0.368595
19,2022,XGB,"2023,2019,2024",11413,4831,1223,22.673908,28.586946,0.679132,0.750200,33.123802,42.196523,0.314466,0.374026,40.015465,49.787490,0.140907,0.433355
20,2023,XGB,"2019,2024",12636,3055,1776,15.776673,20.820327,0.833110,0.843094,28.183838,35.153801,0.257106,0.338988,38.077569,48.837568,0.040080,0.274669
21,2024,XGB,"2023,2019",12636,3718,1113,20.888437,26.773259,0.724032,0.762347,33.078304,41.531158,0.283641,0.296667,30.105400,38.573532,-0.660673,0.171264

## Hyper parameter tuning

In [46]:
import numpy as np
import pandas as pd

from sklearn.model_selection import GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

try:
    from xgboost import XGBRegressor
    xgb_available = True
except Exception as e:
    xgb_available = False
    print("XGBoost not available:", e)

# ---- REQUIRED: df_model, feature_cols, YEAR_COL, TARGET_RAW, y_log already exist ----
# YEAR_COL="year", TARGET_RAW="yield_mean"
# df_model["y_log"] = np.log1p(df_model[TARGET_RAW])

def corr_sq(y_true, y_pred):
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    if np.std(y_true) == 0 or np.std(y_pred) == 0:
        return np.nan
    r = np.corrcoef(y_true, y_pred)[0, 1]
    return float(r*r)

def eval_raw_metrics_from_log_preds(y_true_raw, y_pred_log):
    y_pred_raw = np.expm1(y_pred_log)
    return {
        "mae":  float(mean_absolute_error(y_true_raw, y_pred_raw)),
        "rmse": float(np.sqrt(mean_squared_error(y_true_raw, y_pred_raw))),
        "r2":   float(r2_score(y_true_raw, y_pred_raw)),
        "corr2": float(corr_sq(y_true_raw, y_pred_raw)),
    }

def build_preprocessor(feature_cols):
    num_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])
    return ColumnTransformer([("num", num_pipe, feature_cols)], remainder="drop")

def make_rf_pipeline(feature_cols, params):
    pre = build_preprocessor(feature_cols)
    rf = RandomForestRegressor(
        random_state=42,
        n_jobs=-1,
        **params
    )
    return Pipeline([("pre", pre), ("model", rf)])

def make_xgb_pipeline(feature_cols, params):
    pre = build_preprocessor(feature_cols)
    xgb = XGBRegressor(
        random_state=42,
        n_jobs=-1,
        tree_method="hist",
        **params
    )
    return Pipeline([("pre", pre), ("model", xgb)])

In [47]:
def year_group_cv_score(df, feature_cols, params, model_kind="rf", n_splits=5, seed=42):
    """
    Returns mean CV MAE (raw) across year-group folds, plus mean RMSE/R2/Corr2 for tracking.
    """
    X = df[feature_cols]                 # keep as DataFrame
    y_log = df["y_log"].values
    y_raw = df["yield_mean"].values      # raw target for metrics
    groups = df["year"].values

    gkf = GroupKFold(n_splits=n_splits)

    fold_metrics = []
    for tr_idx, va_idx in gkf.split(X, y_log, groups=groups):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr_log = y_log[tr_idx]
        y_va_raw = y_raw[va_idx]

        if model_kind == "rf":
            pipe = make_rf_pipeline(feature_cols, params)
        else:
            pipe = make_xgb_pipeline(feature_cols, params)

        pipe.fit(X_tr, y_tr_log)
        yhat_va_log = pipe.predict(X_va)
        m = eval_raw_metrics_from_log_preds(y_va_raw, yhat_va_log)
        fold_metrics.append(m)

    out = {
        "mae":  float(np.mean([m["mae"] for m in fold_metrics])),
        "rmse": float(np.mean([m["rmse"] for m in fold_metrics])),
        "r2":   float(np.mean([m["r2"] for m in fold_metrics])),
        "corr2": float(np.mean([m["corr2"] for m in fold_metrics])),
    }
    return out

In [48]:
import xgboost as xgb
from sklearn.model_selection import GroupKFold

def score_params_year_cv_xgb_earlystop(df, feature_cols, params, n_splits=5, early_stopping_rounds=50):
    """
    Robust tuning scorer for XGB with:
    - GroupKFold by year
    - train on log1p(y)
    - evaluate metrics on raw y (expm1(pred))
    - early stopping via xgb.train (native API, version-safe)
    - GPU via tree_method=gpu_hist
    """
    X = df[feature_cols]
    y_log = df["y_log"].values
    y_raw = df[TARGET_RAW].values
    groups = df[YEAR_COL].values

    gkf = GroupKFold(n_splits=n_splits)
    fold_metrics = []

    for tr_idx, va_idx in gkf.split(X, y_log, groups):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr_log = y_log[tr_idx]
        y_va_log = y_log[va_idx]
        y_va_raw = y_raw[va_idx]

        # --- preprocess on train only ---
        pre = build_preprocessor(feature_cols)
        X_tr_t = pre.fit_transform(X_tr)
        X_va_t = pre.transform(X_va)

        # --- DMatrix ---
        dtrain = xgb.DMatrix(X_tr_t, label=y_tr_log)
        dvalid = xgb.DMatrix(X_va_t, label=y_va_log)

        # --- xgb.train params (native) ---
        # Map sklearn-style names to native names when needed
        xgb_params = {
            "objective": "reg:squarederror",
            "eval_metric": "rmse",
            "seed": 42,

            # ✅ GPU
            "tree_method": "hist",
            "device": "cuda",


            # from Optuna
            "eta": params["learning_rate"],
            "max_depth": int(params["max_depth"]),
            "min_child_weight": float(params["min_child_weight"]),
            "subsample": float(params["subsample"]),
            "colsample_bytree": float(params["colsample_bytree"]),
            "gamma": float(params["gamma"]),
            "alpha": float(params["reg_alpha"]),
            "lambda": float(params["reg_lambda"]),
        }

        num_boost_round = int(params.get("n_estimators", 5000))

        booster = xgb.train(
            params=xgb_params,
            dtrain=dtrain,
            num_boost_round=num_boost_round,
            evals=[(dvalid, "valid")],
            early_stopping_rounds=early_stopping_rounds,
            verbose_eval=False
        )

        # predict log, evaluate raw
        yhat_va_log = booster.predict(dvalid)
        m = eval_raw_metrics_from_log_preds(y_va_raw, yhat_va_log)
        fold_metrics.append(m)

    return {k: float(np.mean([m[k] for m in fold_metrics])) for k in fold_metrics[0]}

In [49]:
import optuna

def tune_rf_optuna(df, feature_cols, n_trials=50, n_splits=5):
    def objective(trial):
        params = {
            "n_estimators": trial.suggest_int("n_estimators", 100, 1400),
            "max_depth": trial.suggest_int("max_depth", 1, 40),
            "min_samples_split": trial.suggest_int("min_samples_split", 2, 30),
            "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 15),
            "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", 0.3, 0.5, 0.8]),
            "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
        }
        m = year_group_cv_score(df, feature_cols, params, model_kind="rf", n_splits=n_splits)
        # Optimize raw MAE
        trial.set_user_attr("rmse", m["rmse"])
        trial.set_user_attr("r2", m["r2"])
        trial.set_user_attr("corr2", m["corr2"])
        return m["mae"]

    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

    best_params = study.best_params
    best_mae = study.best_value
    best_meta = study.best_trial.user_attrs
    return study, best_params, best_mae, best_meta


def tune_xgb_optuna(df, feature_cols, n_trials=60, n_splits=5):
    if not xgb_available:
        raise RuntimeError("XGBoost not available in this environment.")

    def objective(trial):
        params = {
            "n_estimators": trial.suggest_int("n_estimators", 100, 2500),
            "learning_rate": trial.suggest_float("learning_rate", 0.00001, 0.01, log=True),
            "max_depth": trial.suggest_int("max_depth", 3, 10),
            "min_child_weight": trial.suggest_float("min_child_weight", 1.0, 20.0, log=True),
            "subsample": trial.suggest_float("subsample", 0.6, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
            "gamma": trial.suggest_float("gamma", 0.0, 5.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 5.0),
            "reg_lambda": trial.suggest_float("reg_lambda", 0.1, 10.0, log=True),
        }
        m = score_params_year_cv_xgb_earlystop(
            df, feature_cols, params,
            n_splits=n_splits,
            early_stopping_rounds=50
        )
        trial.set_user_attr("rmse", m["rmse"])
        trial.set_user_attr("r2", m["r2"])
        trial.set_user_attr("corr2", m["corr2"])
        return m["mae"]

    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

    best_params = study.best_params
    best_mae = study.best_value
    best_meta = study.best_trial.user_attrs
    return study, best_params, best_mae, best_meta

In [ ]:
from sklearn.model_selection import GroupKFold

In [50]:

# (Optional but recommended) restrict tuning to the years you actually plan to train on most of the time
# e.g., use all years 2014-2024:
df_tune = df_model.copy()

target_col = "yield_mean"

# 1) drop missing targets
df_tune = df_tune.dropna(subset=[target_col])

# 2) remove sentinel values if you use them (common in rasters)
df_tune = df_tune[df_tune[target_col] != -9999]   # add others if needed

# 3) enforce positive for log (choose one approach)
df_tune = df_tune[df_tune[target_col] > 0]        # strict (safest for log)

# optional sanity check
assert df_tune[target_col].isna().sum() == 0
assert (df_tune[target_col] <= 0).sum() == 0

rf_study, rf_best_params, rf_best_mae, rf_best_meta = tune_rf_optuna(
    df_tune, feature_cols, n_trials=50, n_splits=5
)
print("\nRF best params:", rf_best_params)
print("RF CV best MAE:", rf_best_mae)
print("RF CV meta:", rf_best_meta)

if xgb_available:
    xgb_study, xgb_best_params, xgb_best_mae, xgb_best_meta = tune_xgb_optuna(
        df_tune, feature_cols, n_trials=60, n_splits=5
    )
    print("\nXGB best params:", xgb_best_params)
    print("XGB CV best MAE:", xgb_best_mae)
    print("XGB CV meta:", xgb_best_meta)

[I 2026-01-25 16:24:42,120] A new study created in memory with name: no-name-148fbc21-34c5-45fd-85ed-a8c81097c6eb

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-25 16:24:51,771] Trial 0 finished with value: 11.469953122673289 and parameters: {'n_estimators': 650, 'max_depth': 4, 'min_samples_split': 29, 'min_samples_leaf': 6, 'max_features': 0.3, 'bootstrap': True}. Best is trial 0 with value: 11.469953122673289.
[I 2026-01-25 16:25:01,871] Trial 1 finished with value: 11.604453776347338 and parameters: {'n_estimators': 1068, 'max_depth': 21, 'min_samples_split': 27, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 11.469953122673289.
[I 2026-01-25 16:25:09,368] Trial 2 finished with value: 11.691217524860782 and parameters: {'n_estimators': 761, 'max_depth': 35, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 11.469953122673289.
[I 2026-01-25 16:25:27,152] Trial 3 finished with value: 12.534819090014635 and parameters: {'n_estimators': 909, 'max_depth': 22, 'min_samples_split': 15, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False}. Best is trial 0 with value: 11.469953122673289.
[I 2026-01-25 16:25:42,905] Trial 4 finished with value: 12.480260712118795 and parameters: {'n_estimators': 860, 'max_depth': 23, 'min_samples_split': 6, 'min_samples_leaf': 11, 'max_features': 0.5, 'bootstrap': False}. Best is trial 0 with value: 11.469953122673289.
[I 2026-01-25 16:25:45,502] Trial 5 finished with value: 11.224333930525688 and parameters: {'n_estimators': 204, 'max_depth': 5, 'min_samples_split': 23, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 5 with value: 11.224333930525688.
[I 2026-01-25 16:26:05,635] Trial 6 finished with value: 11.518865470746364 and parameters: {'n_estimators': 1356, 'max_depth': 36, 'min_samples_split': 20, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 5 with value: 11.224333930525688.
[I 2026-01-25 16:26:14,725] Trial 7 finished with value: 11.873848133717615 and parameters: {'n_estimators': 584, 'max_depth': 16, 'min_samples_split': 26, 'min_samples_leaf': 11, 'max_features': 0.3, 'bootstrap': True}. Best is trial 5 with value: 11.224333930525688.
[I 2026-01-25 16:26:16,923] Trial 8 finished with value: 11.587389657768634 and parameters: {'n_estimators': 137, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 14, 'max_features': 'log2', 'bootstrap': False}. Best is trial 5 with value: 11.224333930525688.
[I 2026-01-25 16:26:22,483] Trial 9 finished with value: 12.567153753380031 and parameters: {'n_estimators': 172, 'max_depth': 36, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False}. Best is trial 5 with value: 11.224333930525688.
[I 2026-01-25 16:26:29,718] Trial 10 finished with value: 10.990644600851464 and parameters: {'n_estimators': 419, 'max_depth': 1, 'min_samples_split': 17, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 10 with value: 10.990644600851464.
[I 2026-01-25 16:26:36,311] Trial 11 finished with value: 10.994691721623564 and parameters: {'n_estimators': 358, 'max_depth': 1, 'min_samples_split': 18, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 10 with value: 10.990644600851464.
[I 2026-01-25 16:26:45,215] Trial 12 finished with value: 12.719534704850311 and parameters: {'n_estimators': 429, 'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 10 with value: 10.990644600851464.
[I 2026-01-25 16:26:52,615] Trial 13 finished with value: 10.989776504054506 and parameters: {'n_estimators': 409, 'max_depth': 1, 'min_samples_split': 19, 'min_samples_leaf': 10, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:27:01,571] Trial 14 finished with value: 12.737234270980087 and parameters: {'n_estimators': 436, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:27:11,914] Trial 15 finished with value: 12.685818033943892 and parameters: {'n_estimators': 544, 'max_depth': 9, 'min_samples_split': 22, 'min_samples_leaf': 9, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:27:18,045] Trial 16 finished with value: 10.992661882071392 and parameters: {'n_estimators': 327, 'max_depth': 1, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:27:29,115] Trial 17 finished with value: 12.792468951612587 and parameters: {'n_estimators': 514, 'max_depth': 14, 'min_samples_split': 17, 'min_samples_leaf': 10, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:27:35,406] Trial 18 finished with value: 12.70937529613066 and parameters: {'n_estimators': 290, 'max_depth': 7, 'min_samples_split': 23, 'min_samples_leaf': 13, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:27:52,231] Trial 19 finished with value: 12.983109640532598 and parameters: {'n_estimators': 724, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:28:08,984] Trial 20 finished with value: 11.934090289887612 and parameters: {'n_estimators': 1145, 'max_depth': 31, 'min_samples_split': 19, 'min_samples_leaf': 7, 'max_features': 0.3, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:28:13,966] Trial 21 finished with value: 10.991596088296168 and parameters: {'n_estimators': 268, 'max_depth': 1, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:28:19,522] Trial 22 finished with value: 12.655745754100446 and parameters: {'n_estimators': 282, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:28:22,065] Trial 23 finished with value: 10.996032319263005 and parameters: {'n_estimators': 111, 'max_depth': 1, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:28:31,122] Trial 24 finished with value: 12.71760577284866 and parameters: {'n_estimators': 459, 'max_depth': 8, 'min_samples_split': 21, 'min_samples_leaf': 10, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:28:35,817] Trial 25 finished with value: 11.456677658130724 and parameters: {'n_estimators': 266, 'max_depth': 40, 'min_samples_split': 9, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:28:42,342] Trial 26 finished with value: 12.695563956221989 and parameters: {'n_estimators': 399, 'max_depth': 5, 'min_samples_split': 16, 'min_samples_leaf': 7, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:28:54,850] Trial 27 finished with value: 12.698363825564886 and parameters: {'n_estimators': 620, 'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 13, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:28:59,226] Trial 28 finished with value: 12.174073482483895 and parameters: {'n_estimators': 237, 'max_depth': 3, 'min_samples_split': 25, 'min_samples_leaf': 9, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:29:09,739] Trial 29 finished with value: 11.653338434696527 and parameters: {'n_estimators': 698, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 5, 'max_features': 0.3, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:29:18,431] Trial 30 finished with value: 11.066388033868929 and parameters: {'n_estimators': 504, 'max_depth': 3, 'min_samples_split': 30, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:29:24,972] Trial 31 finished with value: 10.997196948103067 and parameters: {'n_estimators': 351, 'max_depth': 1, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:29:31,222] Trial 32 finished with value: 10.995981946546388 and parameters: {'n_estimators': 350, 'max_depth': 1, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:29:37,328] Trial 33 finished with value: 12.766823713388932 and parameters: {'n_estimators': 282, 'max_depth': 7, 'min_samples_split': 12, 'min_samples_leaf': 5, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:29:48,241] Trial 34 finished with value: 11.690751715947354 and parameters: {'n_estimators': 814, 'max_depth': 3, 'min_samples_split': 15, 'min_samples_leaf': 8, 'max_features': 0.5, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:29:57,441] Trial 35 finished with value: 11.573866271663787 and parameters: {'n_estimators': 955, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 11, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:30:01,068] Trial 36 finished with value: 12.60714223912763 and parameters: {'n_estimators': 168, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:30:07,626] Trial 37 finished with value: 11.297683098179794 and parameters: {'n_estimators': 670, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': False}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:30:17,890] Trial 38 finished with value: 12.276109452605578 and parameters: {'n_estimators': 570, 'max_depth': 24, 'min_samples_split': 20, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:30:23,492] Trial 39 finished with value: 12.071524219061814 and parameters: {'n_estimators': 351, 'max_depth': 20, 'min_samples_split': 28, 'min_samples_leaf': 9, 'max_features': 0.3, 'bootstrap': False}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:30:27,365] Trial 40 finished with value: 11.595502076415922 and parameters: {'n_estimators': 194, 'max_depth': 12, 'min_samples_split': 16, 'min_samples_leaf': 14, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:30:33,912] Trial 41 finished with value: 10.991580185872989 and parameters: {'n_estimators': 371, 'max_depth': 1, 'min_samples_split': 18, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:30:41,631] Trial 42 finished with value: 12.223998957462783 and parameters: {'n_estimators': 463, 'max_depth': 3, 'min_samples_split': 19, 'min_samples_leaf': 14, 'max_features': 0.8, 'bootstrap': True}. Best is trial 13 with value: 10.989776504054506.
[I 2026-01-25 16:30:48,621] Trial 43 finished with value: 10.989138029152516 and parameters: {'n_estimators': 394, 'max_depth': 1, 'min_samples_split': 24, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 43 with value: 10.989138029152516.
[I 2026-01-25 16:30:55,640] Trial 44 finished with value: 12.68281969407245 and parameters: {'n_estimators': 402, 'max_depth': 5, 'min_samples_split': 25, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 43 with value: 10.989138029152516.
[I 2026-01-25 16:30:59,437] Trial 45 finished with value: 11.884164469591024 and parameters: {'n_estimators': 224, 'max_depth': 2, 'min_samples_split': 23, 'min_samples_leaf': 14, 'max_features': 0.8, 'bootstrap': True}. Best is trial 43 with value: 10.989138029152516.
[I 2026-01-25 16:31:05,570] Trial 46 finished with value: 11.376268080467181 and parameters: {'n_estimators': 632, 'max_depth': 8, 'min_samples_split': 18, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': False}. Best is trial 43 with value: 10.989138029152516.
[I 2026-01-25 16:31:13,642] Trial 47 finished with value: 12.664185054995851 and parameters: {'n_estimators': 490, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 13, 'max_features': 0.8, 'bootstrap': True}. Best is trial 43 with value: 10.989138029152516.
[I 2026-01-25 16:31:19,533] Trial 48 finished with value: 11.685083869711766 and parameters: {'n_estimators': 398, 'max_depth': 3, 'min_samples_split': 26, 'min_samples_leaf': 14, 'max_features': 0.5, 'bootstrap': True}. Best is trial 43 with value: 10.989138029152516.

[I 2026-01-25 16:31:40,268] A new study created in memory with name: no-name-c12c2e7c-93ed-4f22-a0e9-db69ac09b3b7

[I 2026-01-25 16:31:40,258] Trial 49 finished with value: 12.661524598406166 and parameters: {'n_estimators': 1288, 'max_depth': 10, 'min_samples_split': 24, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 43 with value: 10.989138029152516.

RF best params: {'n_estimators': 394, 'max_depth': 1, 'min_samples_split': 24, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}
RF CV best MAE: 10.989138029152516
RF CV meta: {'rmse': 14.401517881781553, 'r2': 0.017291147792120487, 'corr2': 0.18597298304655796}

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-01-25 16:31:47,658] Trial 0 finished with value: 11.821147559510568 and parameters: {'n_estimators': 877, 'learning_rate': 5.5392069434015525e-05, 'max_depth': 4, 'min_child_weight': 3.2449581722574803, 'subsample': 0.8610594662668284, 'colsample_bytree': 0.8019669624187229, 'gamma': 2.042388632115556, 'reg_alpha': 4.836074289756241, 'reg_lambda': 1.7783613807732706}. Best is trial 0 with value: 11.821147559510568.
[I 2026-01-25 16:31:52,056] Trial 1 finished with value: 11.504842236066484 and parameters: {'n_estimators': 367, 'learning_rate': 0.0008530800208298488, 'max_depth': 7, 'min_child_weight': 13.572115581349308, 'subsample': 0.9266667830476026, 'colsample_bytree': 0.6271410788473072, 'gamma': 3.891075624955789, 'reg_alpha': 0.38883641692037896, 'reg_lambda': 3.293560853782267}. Best is trial 1 with value: 11.504842236066484.
[I 2026-01-25 16:31:56,282] Trial 2 finished with value: 11.66536339573441 and parameters: {'n_estimators': 217, 'learning_rate': 0.0010372719959443482, 'max_depth': 9, 'min_child_weight': 18.715207546260817, 'subsample': 0.6598680575090686, 'colsample_bytree': 0.9901427423124846, 'gamma': 0.29270317778332, 'reg_alpha': 3.6871000190929477, 'reg_lambda': 1.806140604989595}. Best is trial 1 with value: 11.504842236066484.
[I 2026-01-25 16:32:05,434] Trial 3 finished with value: 11.74960442415448 and parameters: {'n_estimators': 1304, 'learning_rate': 0.00011737336194903574, 'max_depth': 4, 'min_child_weight': 12.726605368352105, 'subsample': 0.8819644572178806, 'colsample_bytree': 0.9803586600359177, 'gamma': 0.5440376435185246, 'reg_alpha': 3.2177673582535737, 'reg_lambda': 2.834018263158495}. Best is trial 1 with value: 11.504842236066484.
[I 2026-01-25 16:32:08,214] Trial 4 finished with value: 11.516684114499409 and parameters: {'n_estimators': 1582, 'learning_rate': 0.006222599210537016, 'max_depth': 5, 'min_child_weight': 3.7208556463172564, 'subsample': 0.7006083617463236, 'colsample_bytree': 0.964874450726785, 'gamma': 1.4890979319702597, 'reg_alpha': 2.5296302124649244, 'reg_lambda': 0.13317456278531103}. Best is trial 1 with value: 11.504842236066484.
[I 2026-01-25 16:32:15,189] Trial 5 finished with value: 11.867795669334143 and parameters: {'n_estimators': 885, 'learning_rate': 1.4485327276712376e-05, 'max_depth': 4, 'min_child_weight': 2.6554641717064835, 'subsample': 0.8842829104934653, 'colsample_bytree': 0.6517560102532434, 'gamma': 3.8747019845478814, 'reg_alpha': 2.5382223129553916, 'reg_lambda': 2.4584407045007137}. Best is trial 1 with value: 11.504842236066484.
[I 2026-01-25 16:32:18,189] Trial 6 finished with value: 11.477864561824637 and parameters: {'n_estimators': 2161, 'learning_rate': 0.008246902203022332, 'max_depth': 7, 'min_child_weight': 3.9629265454497435, 'subsample': 0.7215136545689195, 'colsample_bytree': 0.6565627086595778, 'gamma': 2.055299651628957, 'reg_alpha': 3.575783420694947, 'reg_lambda': 0.9379295785994243}. Best is trial 6 with value: 11.477864561824637.
[I 2026-01-25 16:32:27,738] Trial 7 finished with value: 11.284192840125545 and parameters: {'n_estimators': 1580, 'learning_rate': 0.0013302572682769706, 'max_depth': 5, 'min_child_weight': 4.180375816950523, 'subsample': 0.6627430674428973, 'colsample_bytree': 0.7996116796138292, 'gamma': 0.41349053574761374, 'reg_alpha': 1.8400631315550724, 'reg_lambda': 0.21129885276655447}. Best is trial 7 with value: 11.284192840125545.
[I 2026-01-25 16:32:31,484] Trial 8 finished with value: 11.144842461767109 and parameters: {'n_estimators': 1989, 'learning_rate': 0.005854460056722381, 'max_depth': 3, 'min_child_weight': 10.35207672829701, 'subsample': 0.6094725412172501, 'colsample_bytree': 0.8764599497586119, 'gamma': 0.15495758747377852, 'reg_alpha': 3.362928868098238, 'reg_lambda': 0.19045363211834193}. Best is trial 8 with value: 11.144842461767109.
[I 2026-01-25 16:32:34,777] Trial 9 finished with value: 11.883291280617561 and parameters: {'n_estimators': 311, 'learning_rate': 1.0307636613057939e-05, 'max_depth': 5, 'min_child_weight': 3.292583107617938, 'subsample': 0.6285470674274878, 'colsample_bytree': 0.9701829843382391, 'gamma': 0.7989321542571792, 'reg_alpha': 2.014903780375783, 'reg_lambda': 0.7390964188578033}. Best is trial 8 with value: 11.144842461767109.
[I 2026-01-25 16:32:39,018] Trial 10 finished with value: 11.48381874816658 and parameters: {'n_estimators': 2458, 'learning_rate': 0.0035245586831492764, 'max_depth': 10, 'min_child_weight': 1.1555452868379605, 'subsample': 0.9939572161428174, 'colsample_bytree': 0.8561738428517851, 'gamma': 2.9828386396306983, 'reg_alpha': 4.992842091591409, 'reg_lambda': 9.63052431842164}. Best is trial 8 with value: 11.144842461767109.
[I 2026-01-25 16:32:44,692] Trial 11 finished with value: 11.124273360061688 and parameters: {'n_estimators': 1914, 'learning_rate': 0.0016652460632174554, 'max_depth': 3, 'min_child_weight': 7.432861400249464, 'subsample': 0.762331051071754, 'colsample_bytree': 0.8630921161103607, 'gamma': 0.1119118507150221, 'reg_alpha': 1.0566374890818313, 'reg_lambda': 0.14987311549874427}. Best is trial 11 with value: 11.124273360061688.
[I 2026-01-25 16:32:49,023] Trial 12 finished with value: 11.1409559059792 and parameters: {'n_estimators': 1890, 'learning_rate': 0.0025441771527800446, 'max_depth': 3, 'min_child_weight': 7.875612110225389, 'subsample': 0.7618100839188225, 'colsample_bytree': 0.8860667354100014, 'gamma': 1.2956083872179214, 'reg_alpha': 0.30228221068365135, 'reg_lambda': 0.33868746160215013}. Best is trial 11 with value: 11.124273360061688.
[I 2026-01-25 16:32:58,614] Trial 13 finished with value: 11.381545839484312 and parameters: {'n_estimators': 1808, 'learning_rate': 0.0003301963973354731, 'max_depth': 3, 'min_child_weight': 7.532852212762531, 'subsample': 0.7758684790501054, 'colsample_bytree': 0.8930749549144368, 'gamma': 1.2937153030782769, 'reg_alpha': 0.2323801503006373, 'reg_lambda': 0.37342840237674785}. Best is trial 11 with value: 11.124273360061688.
[I 2026-01-25 16:33:03,932] Trial 14 finished with value: 11.103405604040956 and parameters: {'n_estimators': 2388, 'learning_rate': 0.0021761205607850284, 'max_depth': 3, 'min_child_weight': 6.847633990587093, 'subsample': 0.7936026056285304, 'colsample_bytree': 0.7557464802449423, 'gamma': 1.1480496504980653, 'reg_alpha': 1.0166450239479403, 'reg_lambda': 0.39973884545010513}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:33:19,489] Trial 15 finished with value: 11.446389219455439 and parameters: {'n_estimators': 2470, 'learning_rate': 0.0004127050472318501, 'max_depth': 6, 'min_child_weight': 6.189898909641217, 'subsample': 0.8109864285148086, 'colsample_bytree': 0.7501763984634299, 'gamma': 4.906081797302954, 'reg_alpha': 1.0808240848260782, 'reg_lambda': 0.10458060265017671}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:33:29,063] Trial 16 finished with value: 11.2961752339119 and parameters: {'n_estimators': 2239, 'learning_rate': 0.0019775415174459136, 'max_depth': 6, 'min_child_weight': 2.15258019144409, 'subsample': 0.8182492975529223, 'colsample_bytree': 0.7423508347262616, 'gamma': 0.9999402252495209, 'reg_alpha': 1.218839938002146, 'reg_lambda': 0.4684711615543696}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:33:51,939] Trial 17 finished with value: 11.342373388006571 and parameters: {'n_estimators': 2160, 'learning_rate': 0.0006022567881775326, 'max_depth': 8, 'min_child_weight': 7.2004352024876805, 'subsample': 0.7339003911271288, 'colsample_bytree': 0.7573741779690444, 'gamma': 1.8701487189193586, 'reg_alpha': 0.9048082974222604, 'reg_lambda': 0.2453749049862514}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:34:04,954] Trial 18 finished with value: 11.589516196130205 and parameters: {'n_estimators': 1645, 'learning_rate': 0.0001422730478462105, 'max_depth': 3, 'min_child_weight': 5.536251373681755, 'subsample': 0.8372959796914632, 'colsample_bytree': 0.6936550864035272, 'gamma': 2.9569143369579685, 'reg_alpha': 1.5958301677091553, 'reg_lambda': 0.5922712172032225}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:34:11,168] Trial 19 finished with value: 11.260805729201008 and parameters: {'n_estimators': 1353, 'learning_rate': 0.00309159864462998, 'max_depth': 4, 'min_child_weight': 1.7422114279026055, 'subsample': 0.7701139994219058, 'colsample_bytree': 0.8292582913820984, 'gamma': 0.10589931816144363, 'reg_alpha': 0.8838315205669247, 'reg_lambda': 0.15920256714447287}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:34:22,812] Trial 20 finished with value: 11.698036992555704 and parameters: {'n_estimators': 995, 'learning_rate': 0.00022105097077842727, 'max_depth': 5, 'min_child_weight': 9.808767245134563, 'subsample': 0.9319402405595851, 'colsample_bytree': 0.9133370039389271, 'gamma': 2.5044010218734916, 'reg_alpha': 1.5215183293677845, 'reg_lambda': 0.27498758571334464}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:34:29,354] Trial 21 finished with value: 11.13496180122673 and parameters: {'n_estimators': 1898, 'learning_rate': 0.0023763406974143756, 'max_depth': 3, 'min_child_weight': 5.317205932303855, 'subsample': 0.7652686549802985, 'colsample_bytree': 0.9154052014041992, 'gamma': 1.1786069671525508, 'reg_alpha': 0.5073639963701538, 'reg_lambda': 0.3770120667579938}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:34:37,780] Trial 22 finished with value: 11.16082022753206 and parameters: {'n_estimators': 2268, 'learning_rate': 0.001435405135715981, 'max_depth': 3, 'min_child_weight': 5.185323985495501, 'subsample': 0.7883452635024756, 'colsample_bytree': 0.9298456967687719, 'gamma': 0.7238298785511703, 'reg_alpha': 0.017376363124382732, 'reg_lambda': 0.43907217443747576}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:34:42,758] Trial 23 finished with value: 11.40225955261623 and parameters: {'n_estimators': 2029, 'learning_rate': 0.003930883463746653, 'max_depth': 4, 'min_child_weight': 9.732610796359797, 'subsample': 0.741156518916384, 'colsample_bytree': 0.8480231703227568, 'gamma': 1.6308241999651616, 'reg_alpha': 0.6344046743617433, 'reg_lambda': 0.1194365414573346}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:34:55,560] Trial 24 finished with value: 11.21892095164812 and parameters: {'n_estimators': 1769, 'learning_rate': 0.0007185398551826378, 'max_depth': 3, 'min_child_weight': 5.624182027156953, 'subsample': 0.7032152547780419, 'colsample_bytree': 0.9407606950208749, 'gamma': 1.0522455769540724, 'reg_alpha': 2.1122437789873194, 'reg_lambda': 0.6241360089719739}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:35:02,775] Trial 25 finished with value: 11.297951804579109 and parameters: {'n_estimators': 2377, 'learning_rate': 0.0019115722855135861, 'max_depth': 4, 'min_child_weight': 4.840456576645163, 'subsample': 0.8350521732493226, 'colsample_bytree': 0.7942497042164972, 'gamma': 2.4013082430498596, 'reg_alpha': 1.3696098748062764, 'reg_lambda': 1.2562843547544824}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:35:05,850] Trial 26 finished with value: 11.27058990146121 and parameters: {'n_estimators': 2103, 'learning_rate': 0.009893070836568018, 'max_depth': 3, 'min_child_weight': 19.302786295677116, 'subsample': 0.6804937612668794, 'colsample_bytree': 0.7041714706053783, 'gamma': 0.6770860064417861, 'reg_alpha': 0.6763582106183879, 'reg_lambda': 0.3037459923320146}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:35:30,688] Trial 27 finished with value: 11.33705471280302 and parameters: {'n_estimators': 1903, 'learning_rate': 0.0006115675494350951, 'max_depth': 6, 'min_child_weight': 13.27185144516049, 'subsample': 0.749890520726094, 'colsample_bytree': 0.7754158245939329, 'gamma': 0.03071207312282742, 'reg_alpha': 0.5854897482088136, 'reg_lambda': 0.17985029896440693}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:35:37,034] Trial 28 finished with value: 11.400827717236485 and parameters: {'n_estimators': 1117, 'learning_rate': 0.0038459714467071306, 'max_depth': 5, 'min_child_weight': 6.873599463611863, 'subsample': 0.7983491255789765, 'colsample_bytree': 0.8386472351532959, 'gamma': 1.1214989408005305, 'reg_alpha': 2.261489114545635, 'reg_lambda': 0.5230756228381662}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:35:51,958] Trial 29 finished with value: 11.794434147422791 and parameters: {'n_estimators': 1536, 'learning_rate': 4.603625518903421e-05, 'max_depth': 4, 'min_child_weight': 2.8981118717030303, 'subsample': 0.8485283277662423, 'colsample_bytree': 0.818306105701506, 'gamma': 1.742537058415232, 'reg_alpha': 1.6838285249524327, 'reg_lambda': 1.016078870372361}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:36:00,956] Trial 30 finished with value: 11.152323822899106 and parameters: {'n_estimators': 2346, 'learning_rate': 0.0013894586048677142, 'max_depth': 3, 'min_child_weight': 9.549818983567505, 'subsample': 0.8729123623536136, 'colsample_bytree': 0.7074246185293095, 'gamma': 2.2059968888904717, 'reg_alpha': 4.34338462259437, 'reg_lambda': 0.254810365897551}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:36:07,747] Trial 31 finished with value: 11.149401788271808 and parameters: {'n_estimators': 1844, 'learning_rate': 0.0023190725030870995, 'max_depth': 3, 'min_child_weight': 7.253552867783952, 'subsample': 0.7549188527185184, 'colsample_bytree': 0.8811252588110636, 'gamma': 1.4597765533999034, 'reg_alpha': 0.0036772523434340787, 'reg_lambda': 0.34798013418452817}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:36:12,387] Trial 32 finished with value: 11.43546494413125 and parameters: {'n_estimators': 492, 'learning_rate': 0.002428233377986337, 'max_depth': 4, 'min_child_weight': 8.34831842326955, 'subsample': 0.7699012720733199, 'colsample_bytree': 0.9160740052886, 'gamma': 1.20694053785041, 'reg_alpha': 0.3867502361830689, 'reg_lambda': 0.3644295542445739}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:36:16,181] Trial 33 finished with value: 11.170864122947798 and parameters: {'n_estimators': 1424, 'learning_rate': 0.005576911877010507, 'max_depth': 3, 'min_child_weight': 12.020465073095078, 'subsample': 0.7148968591023092, 'colsample_bytree': 0.8656729700581264, 'gamma': 0.8812085667678339, 'reg_alpha': 0.9972120316774178, 'reg_lambda': 0.14271437089277053}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:36:26,445] Trial 34 finished with value: 11.34202527377732 and parameters: {'n_estimators': 1729, 'learning_rate': 0.0009635021659849524, 'max_depth': 4, 'min_child_weight': 8.66551085284175, 'subsample': 0.8004726416320767, 'colsample_bytree': 0.9049328050937827, 'gamma': 0.5163250566769149, 'reg_alpha': 0.2860057552729206, 'reg_lambda': 0.7019574424583408}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:36:41,764] Trial 35 finished with value: 11.38016005920868 and parameters: {'n_estimators': 1160, 'learning_rate': 0.001164531435203101, 'max_depth': 8, 'min_child_weight': 6.16105426378359, 'subsample': 0.7618037051401126, 'colsample_bytree': 0.9500798566243955, 'gamma': 0.4115046381163292, 'reg_alpha': 1.2452151243794356, 'reg_lambda': 5.290150181671722}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:36:56,594] Trial 36 finished with value: 11.381733940380457 and parameters: {'n_estimators': 1960, 'learning_rate': 0.000485089946231657, 'max_depth': 4, 'min_child_weight': 16.991868201986588, 'subsample': 0.6848125223347465, 'colsample_bytree': 0.8200118428550974, 'gamma': 2.757712508075486, 'reg_alpha': 0.6432613737691988, 'reg_lambda': 0.24369788817111343}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:36:59,582] Trial 37 finished with value: 11.309753319646209 and parameters: {'n_estimators': 537, 'learning_rate': 0.004909861258163729, 'max_depth': 3, 'min_child_weight': 4.809433956993137, 'subsample': 0.8149580332164786, 'colsample_bytree': 0.9989323231248637, 'gamma': 3.5109935342847325, 'reg_alpha': 2.8671868083382837, 'reg_lambda': 1.6158206382191793}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:37:09,538] Trial 38 finished with value: 11.31921285849532 and parameters: {'n_estimators': 2099, 'learning_rate': 0.0018364084305054628, 'max_depth': 5, 'min_child_weight': 16.289855785883976, 'subsample': 0.9139266912907346, 'colsample_bytree': 0.7320935337964786, 'gamma': 1.4815883011401183, 'reg_alpha': 4.380764402075044, 'reg_lambda': 0.8180750210603723}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:37:15,001] Trial 39 finished with value: 11.326958832990368 and parameters: {'n_estimators': 1683, 'learning_rate': 0.003017122701413626, 'max_depth': 4, 'min_child_weight': 11.319544528783355, 'subsample': 0.7833633069588748, 'colsample_bytree': 0.7808511801865103, 'gamma': 2.1303449592659747, 'reg_alpha': 0.4013174773154489, 'reg_lambda': 0.19651701337621752}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:37:50,946] Trial 40 finished with value: 11.739322651681324 and parameters: {'n_estimators': 2261, 'learning_rate': 4.720903176792034e-05, 'max_depth': 7, 'min_child_weight': 4.344595653616115, 'subsample': 0.7253077543463405, 'colsample_bytree': 0.8859011841917418, 'gamma': 1.870300532918687, 'reg_alpha': 0.8255907053391975, 'reg_lambda': 0.41855020159553913}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:37:55,623] Trial 41 finished with value: 11.18826111209809 and parameters: {'n_estimators': 1959, 'learning_rate': 0.006034099181584964, 'max_depth': 3, 'min_child_weight': 10.692176041911244, 'subsample': 0.6178517068991871, 'colsample_bytree': 0.8735177569691716, 'gamma': 0.25095816305724256, 'reg_alpha': 3.7492619976547576, 'reg_lambda': 0.15956891149612631}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:37:59,908] Trial 42 finished with value: 11.127285224778877 and parameters: {'n_estimators': 1496, 'learning_rate': 0.0065144092178125645, 'max_depth': 3, 'min_child_weight': 8.556667278968275, 'subsample': 0.6450790558870587, 'colsample_bytree': 0.901319180267674, 'gamma': 0.04248409309723247, 'reg_alpha': 3.0146532435726283, 'reg_lambda': 0.21123675448871604}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:38:03,825] Trial 43 finished with value: 11.245138982000995 and parameters: {'n_estimators': 1530, 'learning_rate': 0.007377955257429833, 'max_depth': 3, 'min_child_weight': 8.444498933073564, 'subsample': 0.6476626750868444, 'colsample_bytree': 0.9493873680765651, 'gamma': 0.49609854567477596, 'reg_alpha': 2.79686272269191, 'reg_lambda': 0.294709955526179}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:38:08,889] Trial 44 finished with value: 11.223658050779942 and parameters: {'n_estimators': 1435, 'learning_rate': 0.0042825520442315405, 'max_depth': 3, 'min_child_weight': 3.5052241636791823, 'subsample': 0.6479155471458165, 'colsample_bytree': 0.9243919881233614, 'gamma': 1.3092489185243443, 'reg_alpha': 2.906792071083343, 'reg_lambda': 0.10002009183413178}. Best is trial 14 with value: 11.103405604040956.
[I 2026-01-25 16:38:19,100] Trial 45 finished with value: 11.364904354172648 and parameters: {'n_estimators': 1236, 'learning_rate': 0.0009012111243130663, 'max_depth': 4, 'min_child_weight': 5.971571314011606, 'subsample': 0.6983370750182197, 'colsample_bytree': 0.8988091973030872, 'gamma': 0.2971058366341519, 'reg_alpha': 3.33895467119786, 'reg_lambda': 0.2078395885656282}. Best is trial 14 with value: 11.103405604040956.

In [51]:

# (Optional but recommended) restrict tuning to the years you actually plan to train on most of the time
df_tune = df_model.copy()

target_col = "yield_mean"

# 1) drop missing targets
df_tune = df_tune.dropna(subset=[target_col])

# 2) remove sentinel values if you use them (common in rasters)
df_tune = df_tune[df_tune[target_col] != -9999]   # add others if needed

# 3) enforce positive for log (choose one approach)
df_tune = df_tune[df_tune[target_col] > 0]        # strict (safest for log)

# optional sanity check
assert df_tune[target_col].isna().sum() == 0
assert (df_tune[target_col] <= 0).sum() == 0

rf_study, rf_best_params, rf_best_mae, rf_best_meta = tune_rf_optuna(
    df_tune, feature_cols, n_trials=50, n_splits=5
)
print("\nRF best params:", rf_best_params)
print("RF CV best MAE:", rf_best_mae)
print("RF CV meta:", rf_best_meta)

[I 2026-01-25 16:40:17,880] A new study created in memory with name: no-name-7952972b-bbeb-4dfb-8633-d6b538f8f5bc

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-01-25 16:40:24,145] Trial 0 finished with value: 12.240758756655213 and parameters: {'n_estimators': 380, 'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 4, 'max_features': 0.8, 'bootstrap': True}. Best is trial 0 with value: 12.240758756655213.
[I 2026-01-25 16:40:51,215] Trial 1 finished with value: 12.90928539568535 and parameters: {'n_estimators': 1362, 'max_depth': 17, 'min_samples_split': 26, 'min_samples_leaf': 1, 'max_features': 0.8, 'bootstrap': True}. Best is trial 0 with value: 12.240758756655213.
[I 2026-01-25 16:41:02,302] Trial 2 finished with value: 11.90936284067121 and parameters: {'n_estimators': 704, 'max_depth': 5, 'min_samples_split': 19, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': True}. Best is trial 2 with value: 11.90936284067121.
[I 2026-01-25 16:41:06,469] Trial 3 finished with value: 11.571377113248952 and parameters: {'n_estimators': 368, 'max_depth': 8, 'min_samples_split': 15, 'min_samples_leaf': 14, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 3 with value: 11.571377113248952.
[I 2026-01-25 16:41:25,875] Trial 4 finished with value: 11.650353301782856 and parameters: {'n_estimators': 1321, 'max_depth': 35, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 3 with value: 11.571377113248952.
[I 2026-01-25 16:41:42,820] Trial 5 finished with value: 11.545788371443313 and parameters: {'n_estimators': 1142, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 11, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 5 with value: 11.545788371443313.
[I 2026-01-25 16:42:03,159] Trial 6 finished with value: 12.42573384176887 and parameters: {'n_estimators': 1120, 'max_depth': 31, 'min_samples_split': 25, 'min_samples_leaf': 8, 'max_features': 0.5, 'bootstrap': False}. Best is trial 5 with value: 11.545788371443313.
[I 2026-01-25 16:42:19,962] Trial 7 finished with value: 12.37350493337093 and parameters: {'n_estimators': 1050, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 15, 'max_features': 0.5, 'bootstrap': False}. Best is trial 5 with value: 11.545788371443313.
[I 2026-01-25 16:42:34,163] Trial 8 finished with value: 11.87170256127192 and parameters: {'n_estimators': 946, 'max_depth': 26, 'min_samples_split': 30, 'min_samples_leaf': 13, 'max_features': 0.3, 'bootstrap': True}. Best is trial 5 with value: 11.545788371443313.
[I 2026-01-25 16:42:37,834] Trial 9 finished with value: 11.617302185901758 and parameters: {'n_estimators': 319, 'max_depth': 10, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 5 with value: 11.545788371443313.
[I 2026-01-25 16:42:49,248] Trial 10 finished with value: 11.420523178415602 and parameters: {'n_estimators': 715, 'max_depth': 22, 'min_samples_split': 3, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:43:00,792] Trial 11 finished with value: 11.424232417888367 and parameters: {'n_estimators': 707, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:43:11,251] Trial 12 finished with value: 11.432065339932123 and parameters: {'n_estimators': 657, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:43:20,538] Trial 13 finished with value: 11.42943672478412 and parameters: {'n_estimators': 570, 'max_depth': 39, 'min_samples_split': 2, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:43:22,923] Trial 14 finished with value: 11.541724624599272 and parameters: {'n_estimators': 100, 'max_depth': 25, 'min_samples_split': 7, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:43:35,971] Trial 15 finished with value: 11.45840720352373 and parameters: {'n_estimators': 858, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:43:48,481] Trial 16 finished with value: 11.42152516980643 and parameters: {'n_estimators': 800, 'max_depth': 30, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:44:01,946] Trial 17 finished with value: 11.94821355747313 and parameters: {'n_estimators': 902, 'max_depth': 31, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_features': 0.3, 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:44:07,920] Trial 18 finished with value: 11.5971065210489 and parameters: {'n_estimators': 548, 'max_depth': 29, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:44:20,719] Trial 19 finished with value: 11.531620552742746 and parameters: {'n_estimators': 824, 'max_depth': 39, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:44:28,889] Trial 20 finished with value: 11.449181628653262 and parameters: {'n_estimators': 519, 'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:44:39,972] Trial 21 finished with value: 11.480400288221167 and parameters: {'n_estimators': 717, 'max_depth': 23, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:44:52,389] Trial 22 finished with value: 11.47428255261913 and parameters: {'n_estimators': 779, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 13, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:45:08,790] Trial 23 finished with value: 11.466502737223509 and parameters: {'n_estimators': 1035, 'max_depth': 34, 'min_samples_split': 8, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:45:18,259] Trial 24 finished with value: 11.519288538620284 and parameters: {'n_estimators': 618, 'max_depth': 29, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:45:25,596] Trial 25 finished with value: 11.917539310805706 and parameters: {'n_estimators': 450, 'max_depth': 22, 'min_samples_split': 13, 'min_samples_leaf': 10, 'max_features': 0.3, 'bootstrap': True}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:45:49,431] Trial 26 finished with value: 13.439829111164759 and parameters: {'n_estimators': 957, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 13, 'max_features': 0.8, 'bootstrap': False}. Best is trial 10 with value: 11.420523178415602.
[I 2026-01-25 16:45:53,539] Trial 27 finished with value: 11.415686269098284 and parameters: {'n_estimators': 232, 'max_depth': 35, 'min_samples_split': 9, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': True}. Best is trial 27 with value: 11.415686269098284.
[I 2026-01-25 16:45:58,371] Trial 28 finished with value: 11.418162213058853 and parameters: {'n_estimators': 247, 'max_depth': 35, 'min_samples_split': 17, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': True}. Best is trial 27 with value: 11.415686269098284.
[I 2026-01-25 16:46:01,648] Trial 29 finished with value: 10.995993115170954 and parameters: {'n_estimators': 161, 'max_depth': 1, 'min_samples_split': 16, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:46:05,202] Trial 30 finished with value: 11.88657532653305 and parameters: {'n_estimators': 203, 'max_depth': 2, 'min_samples_split': 17, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:46:11,756] Trial 31 finished with value: 12.735737131854544 and parameters: {'n_estimators': 241, 'max_depth': 34, 'min_samples_split': 23, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:46:17,502] Trial 32 finished with value: 12.780340325680518 and parameters: {'n_estimators': 215, 'max_depth': 37, 'min_samples_split': 21, 'min_samples_leaf': 14, 'max_features': 0.8, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:46:20,450] Trial 33 finished with value: 12.767164193650371 and parameters: {'n_estimators': 106, 'max_depth': 5, 'min_samples_split': 17, 'min_samples_leaf': 14, 'max_features': 0.8, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:46:27,785] Trial 34 finished with value: 12.723387377506853 and parameters: {'n_estimators': 297, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:46:37,050] Trial 35 finished with value: 12.748283945225799 and parameters: {'n_estimators': 439, 'max_depth': 36, 'min_samples_split': 20, 'min_samples_leaf': 14, 'max_features': 0.8, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:46:43,798] Trial 36 finished with value: 12.116891155253255 and parameters: {'n_estimators': 390, 'max_depth': 7, 'min_samples_split': 22, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:46:46,567] Trial 37 finished with value: 11.58622924516558 and parameters: {'n_estimators': 189, 'max_depth': 18, 'min_samples_split': 16, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:47:04,303] Trial 38 finished with value: 12.198319071002771 and parameters: {'n_estimators': 1246, 'max_depth': 33, 'min_samples_split': 13, 'min_samples_leaf': 14, 'max_features': 0.5, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:47:09,483] Trial 39 finished with value: 11.820647099166985 and parameters: {'n_estimators': 289, 'max_depth': 40, 'min_samples_split': 28, 'min_samples_leaf': 13, 'max_features': 0.3, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:47:11,854] Trial 40 finished with value: 11.424146817213101 and parameters: {'n_estimators': 154, 'max_depth': 37, 'min_samples_split': 24, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': False}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:47:18,017] Trial 41 finished with value: 11.52793736265287 and parameters: {'n_estimators': 359, 'max_depth': 32, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:47:22,673] Trial 42 finished with value: 11.501681746617477 and parameters: {'n_estimators': 268, 'max_depth': 29, 'min_samples_split': 18, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:47:30,515] Trial 43 finished with value: 11.481815863237472 and parameters: {'n_estimators': 470, 'max_depth': 27, 'min_samples_split': 14, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:47:33,575] Trial 44 finished with value: 11.541081105228411 and parameters: {'n_estimators': 152, 'max_depth': 31, 'min_samples_split': 9, 'min_samples_leaf': 14, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:47:39,069] Trial 45 finished with value: 11.663601492466565 and parameters: {'n_estimators': 356, 'max_depth': 36, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:48:00,905] Trial 46 finished with value: 11.399036734403762 and parameters: {'n_estimators': 1399, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:48:20,305] Trial 47 finished with value: 11.859906186539641 and parameters: {'n_estimators': 1332, 'max_depth': 4, 'min_samples_split': 16, 'min_samples_leaf': 12, 'max_features': 0.5, 'bootstrap': True}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:48:31,608] Trial 48 finished with value: 11.40080431799844 and parameters: {'n_estimators': 1197, 'max_depth': 8, 'min_samples_split': 19, 'min_samples_leaf': 13, 'max_features': 'log2', 'bootstrap': False}. Best is trial 29 with value: 10.995993115170954.
[I 2026-01-25 16:48:44,218] Trial 49 finished with value: 11.16307546151616 and parameters: {'n_estimators': 1246, 'max_depth': 1, 'min_samples_split': 19, 'min_samples_leaf': 15, 'max_features': 'log2', 'bootstrap': False}. Best is trial 29 with value: 10.995993115170954.

RF best params: {'n_estimators': 161, 'max_depth': 1, 'min_samples_split': 16, 'min_samples_leaf': 15, 'max_features': 0.8, 'bootstrap': True}
RF CV best MAE: 10.995993115170954
RF CV meta: {'rmse': 14.412055606549947, 'r2': 0.015530141677147013, 'corr2': 0.1838825855470832}

In [52]:

if xgb_available:
    xgb_study, xgb_best_params, xgb_best_mae, xgb_best_meta = tune_xgb_optuna(
        df_tune, feature_cols, n_trials=60, n_splits=5
    )
    print("\nXGB best params:", xgb_best_params)
    print("XGB CV best MAE:", xgb_best_mae)
    print("XGB CV meta:", xgb_best_meta)

[I 2026-01-25 16:48:44,237] A new study created in memory with name: no-name-b0ee4fdc-b03f-4fd5-9b84-6aa2792689d2

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-01-25 16:49:02,131] Trial 0 finished with value: 11.33011811574014 and parameters: {'n_estimators': 1532, 'learning_rate': 0.0007941942326899507, 'max_depth': 9, 'min_child_weight': 9.767327932084994, 'subsample': 0.8463509442430166, 'colsample_bytree': 0.6331747639339832, 'gamma': 2.2513095287255, 'reg_alpha': 3.2772440865173174, 'reg_lambda': 9.17241080939572}. Best is trial 0 with value: 11.33011811574014.
[I 2026-01-25 16:49:39,163] Trial 1 finished with value: 11.540901790141778 and parameters: {'n_estimators': 1808, 'learning_rate': 0.00016956005354444616, 'max_depth': 9, 'min_child_weight': 5.957620899404236, 'subsample': 0.7676937496430446, 'colsample_bytree': 0.7097676678059402, 'gamma': 0.4184237052301215, 'reg_alpha': 2.192711748897257, 'reg_lambda': 7.569793210068896}. Best is trial 0 with value: 11.33011811574014.
[I 2026-01-25 16:49:44,515] Trial 2 finished with value: 11.755661146354603 and parameters: {'n_estimators': 552, 'learning_rate': 0.00018839175153529428, 'max_depth': 4, 'min_child_weight': 17.13692498413969, 'subsample': 0.8957466638783826, 'colsample_bytree': 0.767694096673118, 'gamma': 3.6038161412997654, 'reg_alpha': 2.6315180714883066, 'reg_lambda': 0.10103760549225263}. Best is trial 0 with value: 11.33011811574014.
[I 2026-01-25 16:50:05,559] Trial 3 finished with value: 11.494852537265503 and parameters: {'n_estimators': 2240, 'learning_rate': 0.0005638520945313205, 'max_depth': 7, 'min_child_weight': 4.104798222626652, 'subsample': 0.804889578873891, 'colsample_bytree': 0.9473846493850264, 'gamma': 4.4955696811768355, 'reg_alpha': 2.1085236452867298, 'reg_lambda': 2.4954541510175914}. Best is trial 0 with value: 11.33011811574014.
[I 2026-01-25 16:50:12,188] Trial 4 finished with value: 11.230641275718188 and parameters: {'n_estimators': 1409, 'learning_rate': 0.003779529609282309, 'max_depth': 8, 'min_child_weight': 8.03999378557811, 'subsample': 0.6189957170273201, 'colsample_bytree': 0.6481951081576577, 'gamma': 1.3623089239156083, 'reg_alpha': 0.027043636139769123, 'reg_lambda': 0.47198082530432434}. Best is trial 4 with value: 11.230641275718188.
[I 2026-01-25 16:50:15,821] Trial 5 finished with value: 11.769903265612731 and parameters: {'n_estimators': 404, 'learning_rate': 0.00019718297952672293, 'max_depth': 3, 'min_child_weight': 2.369107910453829, 'subsample': 0.709711616798693, 'colsample_bytree': 0.8185783313727371, 'gamma': 4.358280348121154, 'reg_alpha': 1.920366748036444, 'reg_lambda': 3.5834455285813562}. Best is trial 4 with value: 11.230641275718188.
[I 2026-01-25 16:50:45,117] Trial 6 finished with value: 11.8158285169592 and parameters: {'n_estimators': 1802, 'learning_rate': 2.459782895170162e-05, 'max_depth': 9, 'min_child_weight': 3.4031332993407495, 'subsample': 0.9289605270967961, 'colsample_bytree': 0.7158718144677663, 'gamma': 2.074892895690738, 'reg_alpha': 4.19892630524415, 'reg_lambda': 0.22096646890621957}. Best is trial 4 with value: 11.230641275718188.
[I 2026-01-25 16:50:50,617] Trial 7 finished with value: 11.527861448021998 and parameters: {'n_estimators': 1753, 'learning_rate': 0.005196456520870165, 'max_depth': 7, 'min_child_weight': 19.17177252632184, 'subsample': 0.9392692691520954, 'colsample_bytree': 0.9843329834030263, 'gamma': 1.5172669771020515, 'reg_alpha': 0.9882887283455638, 'reg_lambda': 0.12335426293209138}. Best is trial 4 with value: 11.230641275718188.
[I 2026-01-25 16:51:17,993] Trial 8 finished with value: 11.6806611634499 and parameters: {'n_estimators': 1854, 'learning_rate': 9.744630735441539e-05, 'max_depth': 9, 'min_child_weight': 2.967170142369237, 'subsample': 0.7483592659267235, 'colsample_bytree': 0.8204966273854555, 'gamma': 3.532210280863808, 'reg_alpha': 1.8668215767864949, 'reg_lambda': 0.18867993216852005}. Best is trial 4 with value: 11.230641275718188.
[I 2026-01-25 16:51:27,535] Trial 9 finished with value: 11.755058440456034 and parameters: {'n_estimators': 706, 'learning_rate': 0.00019463734256811848, 'max_depth': 5, 'min_child_weight': 2.167909373008896, 'subsample': 0.8575641775416738, 'colsample_bytree': 0.9757825089405823, 'gamma': 1.6042598070155982, 'reg_alpha': 2.2239078917957618, 'reg_lambda': 0.4072204812483131}. Best is trial 4 with value: 11.230641275718188.
[I 2026-01-25 16:51:34,422] Trial 10 finished with value: 11.265406174022427 and parameters: {'n_estimators': 969, 'learning_rate': 0.0049390830923117975, 'max_depth': 6, 'min_child_weight': 1.0034808209910604, 'subsample': 0.6006335664244111, 'colsample_bytree': 0.6139914730581222, 'gamma': 0.23408140767769847, 'reg_alpha': 0.10442823778427801, 'reg_lambda': 0.5707317467555091}. Best is trial 4 with value: 11.230641275718188.
[I 2026-01-25 16:51:43,071] Trial 11 finished with value: 11.233218292335858 and parameters: {'n_estimators': 1055, 'learning_rate': 0.006258615585882725, 'max_depth': 6, 'min_child_weight': 1.1972031396238578, 'subsample': 0.6039420705570527, 'colsample_bytree': 0.6135647013144827, 'gamma': 0.005240293933215068, 'reg_alpha': 0.17030355823026255, 'reg_lambda': 0.724658708066697}. Best is trial 4 with value: 11.230641275718188.
[I 2026-01-25 16:51:46,728] Trial 12 finished with value: 11.445766683895444 and parameters: {'n_estimators': 1116, 'learning_rate': 0.009872612676832912, 'max_depth': 7, 'min_child_weight': 1.0146406742520377, 'subsample': 0.6283874263485079, 'colsample_bytree': 0.667665346563277, 'gamma': 0.8956445261965729, 'reg_alpha': 0.08186933601301999, 'reg_lambda': 1.2721670472967808}. Best is trial 4 with value: 11.230641275718188.
[I 2026-01-25 16:52:00,411] Trial 13 finished with value: 11.15751981226298 and parameters: {'n_estimators': 1199, 'learning_rate': 0.0017134042434054013, 'max_depth': 6, 'min_child_weight': 7.535686671948746, 'subsample': 0.6648584951186706, 'colsample_bytree': 0.6130354377855508, 'gamma': 0.014868582667761037, 'reg_alpha': 0.9071334144668833, 'reg_lambda': 0.9090378411671578}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:52:03,511] Trial 14 finished with value: 11.625122629204451 and parameters: {'n_estimators': 112, 'learning_rate': 0.001951686896240824, 'max_depth': 8, 'min_child_weight': 7.409725689289907, 'subsample': 0.6788514512483526, 'colsample_bytree': 0.8895815928684438, 'gamma': 1.101840259851287, 'reg_alpha': 0.9470864554887519, 'reg_lambda': 1.5414891539034843}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:52:12,381] Trial 15 finished with value: 11.272967512692825 and parameters: {'n_estimators': 1441, 'learning_rate': 0.002215394313531572, 'max_depth': 10, 'min_child_weight': 10.525899078740563, 'subsample': 0.6684066681339933, 'colsample_bytree': 0.6787485299863789, 'gamma': 2.9251971134971075, 'reg_alpha': 0.9029975656402799, 'reg_lambda': 0.3553284208390434}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:52:24,982] Trial 16 finished with value: 11.329686136350787 and parameters: {'n_estimators': 2447, 'learning_rate': 0.0015979353867911852, 'max_depth': 5, 'min_child_weight': 5.702294618229064, 'subsample': 0.9980131195425842, 'colsample_bytree': 0.7448190353526943, 'gamma': 0.7457902720281316, 'reg_alpha': 1.3176712953461491, 'reg_lambda': 0.9396168262009106}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:52:42,261] Trial 17 finished with value: 11.25268433383297 and parameters: {'n_estimators': 1364, 'learning_rate': 0.0007801020447739034, 'max_depth': 8, 'min_child_weight': 10.924066444522829, 'subsample': 0.6643125357807679, 'colsample_bytree': 0.643136623844539, 'gamma': 1.5786409066315104, 'reg_alpha': 0.5727251766831072, 'reg_lambda': 1.9573382474768164}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:52:49,332] Trial 18 finished with value: 11.449269899255924 and parameters: {'n_estimators': 812, 'learning_rate': 0.002354226160116462, 'max_depth': 5, 'min_child_weight': 12.947888494619649, 'subsample': 0.7213293251269437, 'colsample_bytree': 0.8746490851821545, 'gamma': 2.7860659137602046, 'reg_alpha': 4.771396763491059, 'reg_lambda': 0.31568603006679996}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:53:24,703] Trial 19 finished with value: 11.830892527949828 and parameters: {'n_estimators': 2082, 'learning_rate': 1.5157543196471031e-05, 'max_depth': 8, 'min_child_weight': 7.1242947317371685, 'subsample': 0.646488903780263, 'colsample_bytree': 0.6853261989207634, 'gamma': 1.1139505168653983, 'reg_alpha': 1.3898126659370356, 'reg_lambda': 3.472775136929686}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:53:41,798] Trial 20 finished with value: 11.456039389644275 and parameters: {'n_estimators': 1229, 'learning_rate': 0.0004340279083029901, 'max_depth': 6, 'min_child_weight': 4.657248520282987, 'subsample': 0.7011557925798295, 'colsample_bytree': 0.7717149262423731, 'gamma': 0.5463052524381048, 'reg_alpha': 3.3744253216011013, 'reg_lambda': 0.5875470766744916}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:53:46,854] Trial 21 finished with value: 11.323978480994155 and parameters: {'n_estimators': 1023, 'learning_rate': 0.009881815828293042, 'max_depth': 6, 'min_child_weight': 1.4578509151872932, 'subsample': 0.6077969495320248, 'colsample_bytree': 0.6026347186178989, 'gamma': 0.04301187868606531, 'reg_alpha': 0.3523073991572989, 'reg_lambda': 0.7725031024257047}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:53:53,325] Trial 22 finished with value: 11.265357239263613 and parameters: {'n_estimators': 1549, 'learning_rate': 0.004216531362987257, 'max_depth': 4, 'min_child_weight': 1.636224569291108, 'subsample': 0.6326272007164813, 'colsample_bytree': 0.641179794036052, 'gamma': 0.002906001791200541, 'reg_alpha': 0.5708806466105865, 'reg_lambda': 0.6385460194140914}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:54:08,319] Trial 23 finished with value: 11.176133013266766 and parameters: {'n_estimators': 1264, 'learning_rate': 0.0013397581488241023, 'max_depth': 7, 'min_child_weight': 8.077244386971557, 'subsample': 0.6030753190886399, 'colsample_bytree': 0.6029327825279145, 'gamma': 0.5686804853906176, 'reg_alpha': 0.4582100961663743, 'reg_lambda': 1.0424676695527986}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:54:21,571] Trial 24 finished with value: 11.26478784760049 and parameters: {'n_estimators': 1232, 'learning_rate': 0.001264805478142624, 'max_depth': 7, 'min_child_weight': 7.876239377329775, 'subsample': 0.6451805541288924, 'colsample_bytree': 0.666655515787052, 'gamma': 1.2722922831199377, 'reg_alpha': 1.545381291078396, 'reg_lambda': 1.1942903771431024}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:54:41,595] Trial 25 finished with value: 11.232717696589127 and parameters: {'n_estimators': 1618, 'learning_rate': 0.0010400696868897925, 'max_depth': 8, 'min_child_weight': 13.309760744653437, 'subsample': 0.7543785596178205, 'colsample_bytree': 0.7178961014814503, 'gamma': 0.5984718489151145, 'reg_alpha': 0.6510187165304255, 'reg_lambda': 0.43330860637155194}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:54:48,150] Trial 26 finished with value: 11.240055315225977 and parameters: {'n_estimators': 837, 'learning_rate': 0.0033778925465461993, 'max_depth': 7, 'min_child_weight': 5.280918543582842, 'subsample': 0.6860507719388058, 'colsample_bytree': 0.6024636679117135, 'gamma': 1.9072735103594691, 'reg_alpha': 1.1171256161657457, 'reg_lambda': 1.0097581140421472}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:55:12,168] Trial 27 finished with value: 11.370706271316267 and parameters: {'n_estimators': 1289, 'learning_rate': 0.00038231684983608383, 'max_depth': 8, 'min_child_weight': 7.811551138533553, 'subsample': 0.7248905961963112, 'colsample_bytree': 0.6476368724724555, 'gamma': 0.8041721480132676, 'reg_alpha': 1.6216857370921995, 'reg_lambda': 0.2536195123778456}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:55:24,545] Trial 28 finished with value: 11.2145539640772 and parameters: {'n_estimators': 1976, 'learning_rate': 0.0029594831018022153, 'max_depth': 10, 'min_child_weight': 9.262029956419124, 'subsample': 0.7989129042253768, 'colsample_bytree': 0.6986830390136027, 'gamma': 0.4402481628244186, 'reg_alpha': 0.4684677958890624, 'reg_lambda': 1.7449417691364713}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:55:53,341] Trial 29 finished with value: 11.294512037469483 and parameters: {'n_estimators': 2015, 'learning_rate': 0.0007567061071094343, 'max_depth': 10, 'min_child_weight': 13.481003550349701, 'subsample': 0.8141445870420804, 'colsample_bytree': 0.6976495479482314, 'gamma': 0.3873790087438005, 'reg_alpha': 2.9987092351633127, 'reg_lambda': 6.514901650313604}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:56:08,776] Trial 30 finished with value: 11.293884911798084 and parameters: {'n_estimators': 2280, 'learning_rate': 0.0011427958030690948, 'max_depth': 10, 'min_child_weight': 9.026577104630666, 'subsample': 0.7773167385241645, 'colsample_bytree': 0.7364331422352559, 'gamma': 2.2947045689899706, 'reg_alpha': 0.7421535216764221, 'reg_lambda': 2.057050157316913}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:56:18,718] Trial 31 finished with value: 11.241295025701909 and parameters: {'n_estimators': 1628, 'learning_rate': 0.002975325048100939, 'max_depth': 9, 'min_child_weight': 9.235876800459609, 'subsample': 0.8335790528709566, 'colsample_bytree': 0.6362448111001363, 'gamma': 1.0175832462974619, 'reg_alpha': 0.42270487617050423, 'reg_lambda': 1.5055248013527944}. Best is trial 13 with value: 11.15751981226298.
[I 2026-01-25 16:56:31,415] Trial 32 finished with value: 11.153810432582649 and parameters: {'n_estimators': 1438, 'learning_rate': 0.0030358516088445477, 'max_depth': 10, 'min_child_weight': 6.4529461425190675, 'subsample': 0.6385531816974639, 'colsample_bytree': 0.6240132589587605, 'gamma': 0.39048348645526376, 'reg_alpha': 0.0028022186341947752, 'reg_lambda': 3.2167371707856947}. Best is trial 32 with value: 11.153810432582649.
[I 2026-01-25 16:56:50,773] Trial 33 finished with value: 11.13041930832205 and parameters: {'n_estimators': 2039, 'learning_rate': 0.0020104754290378385, 'max_depth': 10, 'min_child_weight': 6.304348883791848, 'subsample': 0.6653297650398029, 'colsample_bytree': 0.6263706543395052, 'gamma': 0.338389078154123, 'reg_alpha': 0.3839632496251091, 'reg_lambda': 4.671144007141974}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:56:59,752] Trial 34 finished with value: 11.328484162018498 and parameters: {'n_estimators': 1139, 'learning_rate': 0.0015977072282752813, 'max_depth': 9, 'min_child_weight': 6.23089091924446, 'subsample': 0.6577978143203057, 'colsample_bytree': 0.6239612599988318, 'gamma': 4.94414599055872, 'reg_alpha': 1.2222351416416877, 'reg_lambda': 5.644512498373732}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:57:14,841] Trial 35 finished with value: 11.48275598859288 and parameters: {'n_estimators': 548, 'learning_rate': 0.000594765371676168, 'max_depth': 10, 'min_child_weight': 3.880715186335556, 'subsample': 0.6909604168930594, 'colsample_bytree': 0.6639664077143229, 'gamma': 0.27398318975786684, 'reg_alpha': 0.003882861142307792, 'reg_lambda': 9.927312497831567}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:57:26,742] Trial 36 finished with value: 11.679769558758911 and parameters: {'n_estimators': 1468, 'learning_rate': 9.98927225408439e-05, 'max_depth': 3, 'min_child_weight': 4.897878234743589, 'subsample': 0.6325824872118763, 'colsample_bytree': 0.6251380067449673, 'gamma': 0.6429617369218531, 'reg_alpha': 0.7975549255271321, 'reg_lambda': 4.52900211607867}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:57:47,312] Trial 37 finished with value: 11.364565800622751 and parameters: {'n_estimators': 1693, 'learning_rate': 0.00029954559492655005, 'max_depth': 5, 'min_child_weight': 6.742660825191261, 'subsample': 0.7376698700978898, 'colsample_bytree': 0.6029170569519446, 'gamma': 0.2539134182451534, 'reg_alpha': 0.31913491709846575, 'reg_lambda': 2.7505935601790648}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:58:01,350] Trial 38 finished with value: 11.252378002756918 and parameters: {'n_estimators': 2254, 'learning_rate': 0.0010137396833422455, 'max_depth': 4, 'min_child_weight': 5.71311568513014, 'subsample': 0.6508305697039105, 'colsample_bytree': 0.6583168406054538, 'gamma': 0.7949607454529193, 'reg_alpha': 2.66068513929007, 'reg_lambda': 2.833628347363591}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:58:06,379] Trial 39 finished with value: 11.413152691529467 and parameters: {'n_estimators': 1902, 'learning_rate': 0.006472244014001073, 'max_depth': 9, 'min_child_weight': 4.001142975391348, 'subsample': 0.6232797416591147, 'colsample_bytree': 0.625782101595401, 'gamma': 1.7654697014885845, 'reg_alpha': 1.7440523599619202, 'reg_lambda': 4.586645481579436}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:58:16,684] Trial 40 finished with value: 11.33033755470768 and parameters: {'n_estimators': 2479, 'learning_rate': 0.001634867203987493, 'max_depth': 9, 'min_child_weight': 14.909818083566929, 'subsample': 0.7021438301139845, 'colsample_bytree': 0.6884171152603571, 'gamma': 3.4496334535847297, 'reg_alpha': 3.690172019742719, 'reg_lambda': 7.299415021142285}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:58:28,200] Trial 41 finished with value: 11.230712432268435 and parameters: {'n_estimators': 2043, 'learning_rate': 0.0033413154788324013, 'max_depth': 10, 'min_child_weight': 11.039298870419115, 'subsample': 0.7813349491360989, 'colsample_bytree': 0.7073252852641975, 'gamma': 0.44829385365163116, 'reg_alpha': 0.44587153824721965, 'reg_lambda': 1.9369510736830344}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:58:47,610] Trial 42 finished with value: 11.138765780925795 and parameters: {'n_estimators': 1915, 'learning_rate': 0.002075670574065361, 'max_depth': 10, 'min_child_weight': 8.392870929841655, 'subsample': 0.8611275399084812, 'colsample_bytree': 0.6335661336218743, 'gamma': 0.3017380016799389, 'reg_alpha': 0.29051260234359155, 'reg_lambda': 3.644692931776397}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:59:07,658] Trial 43 finished with value: 11.157393209555336 and parameters: {'n_estimators': 2172, 'learning_rate': 0.0023369236939534874, 'max_depth': 10, 'min_child_weight': 6.497354123837908, 'subsample': 0.8738502042084598, 'colsample_bytree': 0.6293342848496772, 'gamma': 0.22621748560037913, 'reg_alpha': 0.20565574721415236, 'reg_lambda': 3.753532757705201}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:59:28,551] Trial 44 finished with value: 11.184024240200069 and parameters: {'n_estimators': 2166, 'learning_rate': 0.0025191549059831024, 'max_depth': 10, 'min_child_weight': 6.398556936516501, 'subsample': 0.8699301790829101, 'colsample_bytree': 0.651530057170176, 'gamma': 0.17737961054714102, 'reg_alpha': 0.22972712248672225, 'reg_lambda': 3.7492301785321507}. Best is trial 33 with value: 11.13041930832205.
[I 2026-01-25 16:59:36,287] Trial 45 finished with value: 11.2569621191753 and parameters: {'n_estimators': 2381, 'learning_rate': 0.007050202858763145, 'max_depth': 10, 'min_child_weight': 3.3177557434866944, 'subsample': 0.9035662131814718, 'colsample_bytree': 0.6296533978397312, 'gamma': 0.22168585551306924, 'reg_alpha': 1.0922447417048036, 'reg_lambda': 4.643335254510365}. Best is trial 33 with value: 11.13041930832205.